### ISSUE TITLE
publish to npm for browserify support

### ISSUE THREAD

**Issue by clayzermk1** [airbrake/airbrake-js#104]
[substack/node-browserify](https://github.com/substack/node-browserify) is an extremely popular client-side dependency system that takes advantage of npm. It would be great if you could publish this module to npm.

It would be even greater if you could add compiled javascripts (min and non) to a dist directory or add a package.json install script to build the files. :grin:

Cheers! :beers:

**Comment by slorber** [comment]
Is this still unsupported? I see a package.json with a main file but maybe it does not work yet with browserify?

**Comment by vmihailenco** [comment]
There is early preview here https://github.com/airbrake/airbrake-js/pull/132

**Comment by vmihailenco** [comment]
Should be fixed on master. Closing.
