### ISSUE TITLE
Missing version 1.6.6

### ISSUE THREAD

**Issue by juanisorondo** [airbrake/airbrake-js#1042]
Commit a465b57dc9aaeae3fb8fda51a1867c76685954c8 used to be tagged as v1.6.6, version which our application depended on.
It appears this version tag has been deleted, and I would like to ask why?

Furthermore, the nearest downwards version (1.4.2) is clearly wrong since it is further in the future that 1.6.6 used to be, breaking backwards compatibility.

**Comment by scottsbaldwin** [comment]
@sgray can you take a look at this?

**Comment by sgray** [comment]
Hi, @juanisorondo. I'm not sure when this tag was deleted, but I don't think it was anytime recently. Presumably, this is related to https://github.com/airbrake/airbrake-js/issues/602. I recommend upgrading to the latest `@airbrake/browser` or `@airbrake/node` notifier if you can. If that doesn't work for you, you can continue to depend on that commit by its SHA.
