### ISSUE TITLE
notice.id & notice.url do not show up in response

### ISSUE THREAD

**Issue by capsulejj** [airbrake/airbrake-js#1043]
npm v2.1.5 @airbrake/browser

This is what mentioned in the document:

let promise = airbrake.notify(`user id=${user_id} not found`);
promise.then((notice) => {
  if (notice.id) {
    console.log('notice id', notice.id);
  } else {
    console.log('notify failed', notice.error);
  }
});

However, in real code, notice.id is undefined.
Would you please revise?
Thanks!

**Comment by sgray** [comment]
Are you sure the request is succeeding? I've just tested this locally, and `notice.id` is defined as expected.
