### ISSUE TITLE
CORS issues with @airbrake/browser

### ISSUE THREAD

**Issue by paul-mesnilgrente** [airbrake/airbrake-js#1063]
# 🐞 bug report

### Affected Package
@airbrake/browser

### Description

I used the React example in a rails/react app but I'm getting this error:

> notify failed: TypeError: Network request failed

due to (in firefox, equivalent error in chrome)

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.airbrake.io/api/v3/projects/124730/notices?key=REDACTED. (Reason: CORS request did not succeed).

## 🔥 Exception or Error
Also got:
<pre><code>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://notifier-configs.airbrake.io/2020-06-18/config/124730/config.json?&notifier_name=airbrake-js%2Fbrowser&notifier_version=2.1.5&os=Mozilla%2F5.0%20(X11%3B%20Ubuntu%3B%20Linux%20x86_64%3B%20rv%3A89.0)%20Gecko%2F20100101%20Firefox%2F89.0&language=JavaScript. (Reason: CORS request did not succeed).
</code></pre>

## 🌍  Your Environment

**@airbrake/browser: 2.1.5**

**Comment by scottsbaldwin** [comment]
Thanks @paul-mesnilgrente, we'll take a look!

**Comment by paul-mesnilgrente** [comment]
I created a simple reproducible example here: https://github.com/paul-mesnilgrente/rails-react-airbrake

The README is showing the instructions to have the server running locally.

**Comment by scottsbaldwin** [comment]
@paul-mesnilgrente please go to your project settings page and regenerate the API key since your original description above included your API key (and this is a public repo). I have edited the description to redact your API key.

**Comment by paul-mesnilgrente** [comment]
Ah true, will do!

**Comment by scottsbaldwin** [comment]
Thanks for the sample repo!

**Comment by paul-mesnilgrente** [comment]
Note that the important commit is here: https://github.com/paul-mesnilgrente/rails-react-airbrake/commit/2145da92a2013b5d084158d8ca6f43901acb6599

**Comment by scottsbaldwin** [comment]
@thompiler could you take a look into this?

**Comment by thompiler** [comment]
>@thompiler could you take a look into this?

Yes, I will take a look at this. 👍 

Thanks for providing a full example app!

**Comment by paul-mesnilgrente** [comment]
Let me know if you hit issues running it :)

**Comment by thompiler** [comment]
>Let me know if you hit issues running it :)

Will do. Thanks!

**Comment by paul-mesnilgrente** [comment]
Hi! I could reproduce the problem in a simple create-react-app to make sure it wasn't related to some rails config. I actually found that problem is coming from the "AdBlock Plus" extension I use

![image](https://user-images.githubusercontent.com/4416830/123810855-08218880-d8f3-11eb-9955-c9c8473e003d.png)

**Comment by thompiler** [comment]
Hi Paul!

Thanks so much for the update! Glad you found the cause of the issue. That's good to know about the extension. I actually use that it as well. 

Let us know if anything else comes up.

Happy Airbraking!

**Comment by paul-mesnilgrente** [comment]
It's interesting that you never had this issue. Do you have an explanation why?

**Comment by thompiler** [comment]
>It's interesting that you never had this issue. Do you have an explanation why?

I'm not sure, if you'd like I can try fresh with your example though. We have run into adblocker issues in the past with extensions like Ghostery and other "tracker blocking" services lumping in Airbrake with ad trackers. I don't remember adblock plus coming up but it may have.
