### ISSUE TITLE
Loading airbrake.js on-demand in the browser

### ISSUE THREAD

**Issue by rickthepick** [airbrake/airbrake-js#1069]
I don't want to load airbrake-js for my lightweight pages when the page loads.  Instead I want to load airbrake-js after the error occurs by dynamically attaching a "script" tag to the page.  Is there support for this?

**Comment by seuros** [comment]
Airbrake need to be loaded to catch the error the first time.

**Comment by scottsbaldwin** [comment]
@sgray can you think of a way to do this? I haven't tried this, but I suppose if you were sending errors to Airbrake manually something like this could work:

```
function ensureAirbrakeIsLoaded() {
  // dynamically load airbrake if it hasn't been loaded
}

function notifyAirbrake(err) {
  ensureAirbrakeIsLoaded();
  airbrake.notify(err);
}

try {
  // some risky code that will throw an exception
} catch(err) {
  // use a wrapper to ensure airbrake is loaded, then notify
  notifyAirbrake(err);
}
```

**Comment by sgray** [comment]
Yes, that setup should definitely work. I can't think of a way to enable automatic error catching, but the manual `try/catch` like you've written would work fine to load Airbrake on-demand.

**Comment by scottsbaldwin** [comment]
Thanks @sgray
