### ISSUE TITLE
Add Node.js integration

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/airbrake-js#120]

**Comment by ruffrey** [comment]
We're seeing an issue where this will install manually with `npm i airbrake-js` or `npm i --save airbrake`. However when it is just in the `package.json` of a project, it will not install (such as during a build). Not sure what is going on here but I reproduced it locally on OSX and Ubuntu.

**Comment by kyrylo** [comment]
Closed in favour of https://github.com/airbrake/node-airbrake.
