### ISSUE TITLE
Raw eval of URL params - Security Issue

### ISSUE THREAD

**Issue by bpourriahi** [airbrake/airbrake-js#121]
This executes an alert: oursite.com?aaa='-alert(String.fromCharCode(88,83,83))-'

It doesn't happen in Chrome or Firefox, as they escape single quotes. But it does happen on Safari and Opera.

**Comment by vmihailenco** [comment]
Hi,

I can't reproduce it using Safari 8.0.2 and Opera 12.16 on Ubuntu. Overall looking at the notifier source code I can't find any uses of `eval` that can cause this issue: https://raw.githubusercontent.com/airbrake/airbrake-js/master/airbrake.js

Can you try to:
- Checkout this repo.
- Start grunt server:

```
grunt serve
```

- Open: http://localhost:9001/examples/jquery.html?aaa='-alert(String.fromCharCode(88,83,83))-'

- Make sure that you see an alert. You can trigger an exception by clicking on the button.
