### ISSUE TITLE
Airbrake-js CORS issue with errbit

### ISSUE THREAD

**Issue by shivanibhanwal** [airbrake/airbrake-js#122]
Thank you for the nice package/plugin for Js error.
I am using airbrake-js with errbit and enhancing errbit API to support V3
And I have integrated airbrake-js to the EMBER.js app.

But I am running into an issue because of the CORS problem 
As `report ` function of airbrake.js is setting header for the content-type but not for the
cross origin support.
So whenever errbit receives a request is OPTIONS request instead of POST request.
Could you suggest me is there a way to set it for Airbrake or am i missing any thing?

I referred all these links https://github.com/airbrake/airbrake-js/pull/108

As they are not using errbit so they do not have this issue https://github.com/airbrake/airbrake-js/issues/5

**Comment by vmihailenco** [comment]
Hi,

>So whenever errbit receives a request is OPTIONS request instead of POST request.

This is CORS preflight request: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests . errbit should respond to such requests with following headers set:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: accept, origin, x-requested-with, Content-Type
Access-Control-Allow-Methods: OPTIONS,GET,PUT,POST
```

>And I have integrated airbrake-js to the EMBER.js app.

Is there anything reusable that we can add to the airbrake-shim?

**Comment by shivanibhanwal** [comment]
@vmihailenco Actually I fixed it by adding rack-cors on Errbit side.
I tried setting headers on the airbrake.js side but it did not help much
Issue was same as the receiving server has to accept it and allow it.
