### ISSUE TITLE
Unable to post sourcemaps to /v4/projects/:projectId/sourcemaps

### ISSUE THREAD

**Issue by supersime** [airbrake/airbrake-js#1222]
We are using `curl` to `POST` sourcemaps to airbrake in a bash script. It has previously worked and about a week ago stopped working and we have started getting 401 errors.

We have not changed any code on our end. This issue is not specific to the airbrake-js library however your Customer Success Manager suggested I raise the issue here.

This is the `curl` command we use:

```
    curl "https://airbrake.io/api/v4/projects/$airbrake_project_id/sourcemaps" \
        -X POST \
        -H "Authorization: Bearer $airbrake_project_id" \
        -F file=@./tmp-$tag/assets/${fileName} \
        -F name="https://assets.my.minuteme.com/${tag}/assets/${fileName}" \
```

and this is the response we are now getting:

```
{"code":401,"type":"Unauthorized","message":"Project not found or access denied"}
```

The project Id is 187285.

**Comment by supersime** [comment]
Ah my bad.
I took a copy of our primary script (which does a whole lot more than just uploading the sourcemaps), so I could just upload the sourcemaps. And, of course, a copy and paste error.
I see now that in the `Authorization` header I was passing in the project Id and not the project Key.
Apologies. Hopefully you didn't even get to spend any time on this!
There definitely was an issue but you guys must have resolved it.
I'm closing the issue.

**Comment by nthatcher-airbrake** [comment]
@supersime Happy to hear that you were able to get this resolved!
