### ISSUE TITLE
"Error: Permission denied to access property 'external'" in Firefox

### ISSUE THREAD

**Issue by lacco** [airbrake/airbrake-js#123]
I just tried to use airbrake in my web application, everything seems to be fine on Google Chrome. When an error occurs on Firefox, no notification is sent to Airbrake, and I get ```Error: Permission denied to access property 'external'```.

I tried to track it down, the error occurs in ```airbrake.js```, line 591, in the ```getPath``` method:

![airbrake_error](https://cloud.githubusercontent.com/assets/17513/6188013/920a07c6-b38d-11e4-8094-ce2114e90882.png)

I don't know what this function is really doing, but the problem seems to be that ```seen[i]``` is an object on which ```path[0]``` / ```external``` can't be called. I have no clue what ```seen[i]``` can be  in this case and how to fix it, any ideas for further debugging?

**Comment by vmihailenco** [comment]
Hi,

Thanks for the report. Should be fixed in master. We will upload new version to the CDN on Monday.

**Comment by lacco** [comment]
Did you already find some time to update the CDN? It seems that it is still delivering the old version?

**Comment by vmihailenco** [comment]
I forgot to bump version :/ @benarent will upload it again today.

**Comment by lacco** [comment]
Thx!

**Comment by lacco** [comment]
Thank you very much, current version has now fixed my issue!

**Comment by vmihailenco** [comment]
Thank you for the report.

**Comment by benarent** [comment]
Great :) It took a while to purge the CDNS
