### ISSUE TITLE
"cannot jsonify notice"

### ISSUE THREAD

**Issue by lacco** [airbrake/airbrake-js#125]
Every few days I get an error like ```Production Error: cannot jsonify notice (length=64670 maxLength=64000)```. It seems like it is thrown in https://github.com/airbrake/airbrake-js/blob/f38faa0acb2e8c73720cf1920d460c806ae0edf4/src/util/jsonify_notice.coffee , and I have no idea how to debug this. Could you help out here?

**Comment by vmihailenco** [comment]
@benarent will upload v0.3.12 to the CDN today. New version will report problematic JSON in the params, so you can look at it and say why it is so large. Then we can decide how to improve JSON serialization.

**Comment by lacco** [comment]
Thank you very much, sounds like a good plan. I'll let you know as soon as this error occurs another time!

**Comment by benarent** [comment]
@lacco It's uploaded, it may take a bit longer to clear the cache on /0.3/ but you can get the file from http://ssljscdn.airbrake.io/0.3.12/airbrake.js for testing.

**Comment by benarent** [comment]
The CDN has propagated. Marking this as closed.

Ben

**Comment by lacco** [comment]
I now have some new ```airbrake-js: cannot jsonify notice``` errors, but I am not sure what exactly changed to make debugging possible. Under the "Parameters" tab are see the following, is this the expected change?

```
{
  "arguments": [
    {
      "duration": 500,
      "elem": {},
      "opts": {
        "duration": 500,
        "old": false,
        "queue": "fx",
        "specialEasing": {}
      },
      "originalOptions": {
        "duration": 500,
        "old": false,
        "queue": "fx"
      },
      "originalProperties": {
        "opacity": "show"
      },
      "props": {},
      "startTime": 1426073571137,
      "tweens": []
    }
  ]
}
```
