### ISSUE TITLE
security update: cross-fetch

### ISSUE THREAD

**Issue by ldeveber** [airbrake/airbrake-js#1264]
# 🐞 bug report

### Affected Package

 The issue is caused by package @airbrake/....
browser and maybe node too...?

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

<img width="1253" alt="Screen Shot 2022-06-23 at 10 42 33 AM" src="https://user-images.githubusercontent.com/4457752/175327093-1564c05e-c268-42ee-b2f8-5faa0f8cf4d1.png">

https://github.com/advisories/GHSA-r683-j2x4-v87g

## 🔬 Minimal Reproduction

 https://gist.github.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**@airbrake/\* version:**
<pre><code>

</code></pre>

**Anything else relevant?**

maybe add dependabot for security updates?

**Comment by ldeveber** [comment]
Would it be possible to get a release soon for this @kyrylo ? Thank you in advance ^_^

**Comment by kyrylo** [comment]
Sure thing 👌
Could you confirm that this change actually solves the problem for you?

**Comment by ldeveber** [comment]
> Sure thing 👌 Could you confirm that this change actually solves the problem for you?

It does, thank you so much!

**Comment by ldeveber** [comment]
> Sure thing 👌 Could you confirm that this change actually solves the problem for you?

is there a planned time already for when the next release will be?

**Comment by kyrylo** [comment]
Thanks for confirming! There's no planned time yet, but I think next week I'll release a new version. We have blackouts here in Ukraine every day, and I need to make sure certain things work as expected.

**Comment by ldeveber** [comment]
> Thanks for confirming! There's no planned time yet, but I think next week I'll release a new version. We have blackouts here in Ukraine every day, and I need to make sure certain things work as expected.

Stay safe :(

**Comment by kyrylo** [comment]
Thanks, Lesley! I just released [v2.1.8](https://www.npmjs.com/package/@airbrake/browser/v/2.1.8?activeTab=versions). Enjoy!
