### ISSUE TITLE
airbrake-shim.js : console is not always available in IE9

### ISSUE THREAD

**Issue by fletcherm** [airbrake/airbrake-js#127]
Hello!

Sadly, window.console is not always available in IE9. If the tools window isn't open, the object doesn't exist. Lame. More information here : http://thisbythem.com/blog/whats-up-with-the-js-console-in-ie9/

To add further sadness, the airbrake-shim wants to log a warning if jQuery is not available. This leads to trouble if you're on IE9 and jQuery isn't available. (Though, happily, the rest of airbrake-js is happy to report the "console is undefined" error. :))

The offending line is here: https://github.com/airbrake/airbrake-js/blob/master/airbrake-shim.coffee#L106

I see a few options here : 
1) In this else block, guard against console being unavailable. Details here : http://stackoverflow.com/a/14714140
2) Ensure the console object and functions are always available. This could work but has side effects (window.console will live beyond airbrake-shim). Details here : http://stackoverflow.com/a/10183573
3) Remove the warning. In my experience it isn't adding a lot of value, but perhaps does for others.

What do you think?

**Comment by rwolffgang** [comment]
We see the same, also in more modern browsers like Chrome. It occurs a few hundred times per day and it looks like bad quality for an error tracker to throw errors itself.

Any prognosis when this will be addressed?

**Comment by vmihailenco** [comment]
Thanks for the report. I hopefully fixed it.

**Comment by fletcherm** [comment]
Thanks. It looks good; I personally won't try it until later on.
