### ISSUE TITLE
airbrake-shim : Error in console

### ISSUE THREAD

**Issue by jennyfer** [airbrake/airbrake-js#130]
Hello,

I use airbrake-shim in a rails 3 project and am having some troubles. In FF, the console reported a `TypeError: a.document is undefined`.
In Chrome & IE10, the console reported a `Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined`.
Both referring to the airbrake.min.js file.
Could you help me please ?

**Comment by vmihailenco** [comment]
That error means that `window.document` is undefined, which does not make much sense... I will take at this again later, but I don't have good ideas...

**Comment by vmihailenco** [comment]
What version of the notifier do you use?

**Comment by jennyfer** [comment]
I use the 3.2.1 version

**Comment by vmihailenco** [comment]
That is very unlikely since latest version of the JavaScript notifier is 0.3.12. Do you load notifier from the CDN at https://ssljscdn.airbrake.io/0.3/airbrake.min.js ?

**Comment by jennyfer** [comment]
yes and the error is referred to this file.

**Comment by vmihailenco** [comment]
Closing since I can't reproduce it and we are changing the way we distribute notifier.
