### ISSUE TITLE
Error with jQuery.Callbacks wrapping in airbrake-shim

### ISSUE THREAD

**Issue by Gowiem** [airbrake/airbrake-js#133]
At my company we're using airbrake-js to report errors back to our errbit instance. We're seeing a weird error accompany other errors, for example we get a 409 conflict response from our server (causing our jQuery call to blow up) and this error comes through at the same time. This is consistent. This is the error: 

`: function () { return cbAdd.apply(this, wrapArguments(arguments)); }` 

It has an empty backtrace. I searched our codebase for this line of code and it's coming from our airbrake-shim.js file. This makes me think Airbrake is somehow reporting on itself which seems really odd. Now this might not be Airbrake's fault as it's totally possible that our setup code is breaking this so for full disclosure this is how we're logging to Airbrake:

// config.js
```javascript
  //... 
  // Catch all internal RSVP errors and log to console.
  Ember.RSVP.on('error', function(error) {
    Artisan.Logger.error(error, "RSVP Error");
  });

  Ember.onerror = function(error) {
    Artisan.Logger.error(error, "Ember Error");
  };

  window.onerror = function(error) {
    Artisan.Logger.error(error, "Window Error");
  };

  $(document).ajaxError(function(event, jqXHR, ajaxSettings, error) {

    // If we aborted an ajax request then we don't consider that an error, bail out.
    if (jqXHR.status === 0 && jqXHR.statusText === 'abort') {
      return;
    }

    Artisan.Logger.error(error, "AJAX Error");
  });
```

// logger.js
```javascript
  var errorFunc = console.error;
 
  //... 
  Logger.error = function(errorObject) {

    // Log to Airbrake if it's been added to the Window.
    if (window.Airbrake) {
      window.Airbrake.push(errorObject);
    }

    var args = buildArgs("ERROR", arguments);
    errorFunc.apply(console, args);
  };
```
 
Has anyone seen this? Any steps I can take to debug this further?

**Comment by vmihailenco** [comment]
Airbrake notifier does not use jQuery so I don't see how fault in jQuery can affect it. I also did not see such error message before. Sorry.

**Comment by Gowiem** [comment]
@vmihailenco I didn't know it wasn't using jQuery, but what I'm referring to is [this function](https://github.com/airbrake/airbrake-js/blob/master/airbrake-shim.js#L104). Specifically this code in airbrake-shim.js:

```
  // Reports exceptions thrown in jQuery callbacks.
  var jqCallbacks = jQuery.Callbacks;
  jQuery.Callbacks = function(options) {
    var cb = jqCallbacks(options),
        cbAdd = cb.add;
    cb.add = function() {
      return cbAdd.apply(this, wrapArguments(arguments));
    }
    return cb;
  }
```

I'm going to try to debug this further later this week and I'll report back if I find anything.

**Comment by vmihailenco** [comment]
Please reopen if you find anything.
