### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by enapupe** [airbrake/airbrake-js#134]
What has jQuery to do with Airbrake? Is it a fundamental dependency? 
I'm working with AngularJS without jQuery and want to make basic error submitting to Airbrake..
Maybe I just have to read the restAPI and implement it myself?
What do you guys think is the best approach?
Thanks

**Comment by vmihailenco** [comment]
Airbrake-js does not have dependency on jQuery. airbrake-shim only contains jQuery instrumentation to catch exceptions thrown in jQuery callbacks and promises. You can remove it.
