### ISSUE TITLE
Using airbrake with angular

### ISSUE THREAD

**Issue by govindpatel** [airbrake/airbrake-js#136]
- How to use airbrake with angular.
I tried googling around and I found this : https://help.airbrake.io/kb/installing-airbrake-in-your-application/airbrake-and-angular

But in this the script used is "airbrake-shim.js". I am not able to find this file anywhere in this repository.

and then I saw this : https://www.facebook.com/airbrake.io/posts/10203200553165730

I am not sure how can I use airbrake with my angular project.

**Comment by vmihailenco** [comment]
Did you check https://github.com/airbrake/airbrake-js/blob/master/examples/legacy/app.js and https://github.com/airbrake/airbrake-js/blob/master/examples/requirejs/app.js ? If so, how we can improve those examples?

We use following exceptionHandler:

```
mod.factory '$exceptionHandler', ($log, config) ->
  airbrake = new airbrakeJs.Client(
    projectId: config.airbrake.projectId
    projectKey: config.airbrake.key
  )
  airbrake.setEnvironmentName(config.envName)

  (exception, cause) ->
    $log.error(exception)
    exception.params = {cause: cause}
    airbrake.push(exception)
```
