### ISSUE TITLE
Compile standalone script error

### ISSUE THREAD

**Issue by lessmind** [airbrake/airbrake-js#144]
I try to follow the instructions in README to compile a standalone script for our project.

And this is what I got
```shell
Error: Cannot find module './internal/merge' from '/home/user/dev/airbrake-js/dist'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)
```

I checked the coffee script source code, it required these modules which defined in **src/\*.coffee**.
But none of these files have been compile into **dist/\*.js**.

What else should I do?

BTW, I don't understand why this project can't build a client script file that we could simply include it.

**Comment by vmihailenco** [comment]
Let me know what confused you and I will try to improve readme.

**Comment by lessmind** [comment]
Sorry I'm not a native English speaker, maybe there's nothing wrong but I just can't understand the instructions.

The Setup section in README made me believe that I should use browserify to compile a standalone version myself to deploy, but the only thing I have to do is to include dist/client.js in html header.

And when you used the script dist/client.js, the object init should like this:
```javascript
// AirbrakeClient doesn't exist
// new AirbrakeClient({projectId: 1, projectKey: 'abc'});
var airbrake = new airbrakeJs.Client();
airbrake.setProject('PROJECT_ID', 'API_KEY');
airbrake.setEnvironmentName('ENV_NAME');
```
