### ISSUE TITLE
Initialization with jQuery -> Cannot read property 'jquery' of undefined

### ISSUE THREAD

**Issue by Piioo** [airbrake/airbrake-js#145]
When I add this to my initialization:

    var airbrake = new airbrakeJs.Client({projectId: 1, projectKey: 'abc'});
    if (window.jQuery) {
      airbrakeJs.instrumentation.jquery(airbrake, jQuery);
    }

Cannot read property 'jquery' of undefined

airbrakeJs
-> Object {}

What I doing wrong?

**Comment by vmihailenco** [comment]
Hi,

Most likely you did not include `instrumentation/jquery.js` script. For example
- https://github.com/airbrake/airbrake-js/blob/master/examples/legacy/index.html#L8
- or if you use requirejs https://github.com/airbrake/airbrake-js/blob/master/examples/requirejs/app.js#L7

**Comment by Piioo** [comment]
Thx you right. I have installed airbrake-js with bower and Bowerfile in Ruby on Rails and sprocket was not known *instrumentation/jquery.js*.

**Comment by ericjames** [comment]
I am having this problem too.  Is instrumentation a modified version of jquery specific to airbrake? how come when I try to load jquery 2.1.4, it won't work.  @vmihailenco

**Comment by vmihailenco** [comment]
airbrake-js jQuery instrumentation just adds some hooks to standard jQuery version - https://raw.githubusercontent.com/airbrake/airbrake-js/master/src/instrumentation/jquery.coffee. It should work with 2.1.4, but I did not test it.

**Comment by ericjames** [comment]
Okay that's what I was getting at, it sounds like this file is adding hooks, but it doesn't appear to actually just be a plain jQuery library.

I was trying to load airbrake and a standard jQuery library, without this instrumentation file.

I would recommend renaming the file jquery-hooks or something so people understand what this file is doing (naming it jquery.min.js implies it is a standard library file)

**Comment by kiflay** [comment]
I am getting the same error, 'Uncaught TypeError: Cannot read property 'jquery' of undefined'
I have checked if jQuery is not defined, it returns false.
--> typeof jQuery == 'undefined'
--> false
using jQuery returns an object`` instead the 'div element'
--> jQuery('#featured-tags__menu__tag1')
--->Object {ready: function}

**Comment by vmihailenco** [comment]
Then just don't include instrumentation/jquery.js file...

**Comment by kiflay** [comment]
@vmihailenco  I don't have instrumentation/jquery.js on the page.
