### ISSUE TITLE
Best way to integrate with a rails project?

### ISSUE THREAD

**Issue by harlantwood** [airbrake/airbrake-js#146]
What is the best way to integrate JS error reporting into my rails project?  Some options:

1. Copy this file into my local project: https://raw.githubusercontent.com/airbrake/airbrake-js/master/dist/client.js
2. Include from CDN, eg https://ssljscdn.airbrake.io/airbrake.min.js

I would think # 2, as that should always give me the latest greatest version of your code?

BTW, I got # 2 by modifying a URL found in [this article](https://airbrake.io/blog/notifier/airbrake-ruby-gem-3-1-5-airbrake-js-0-3-beta).

Thanks!

**Comment by harlantwood** [comment]
Also, # 1 and # 2 are different code -- which is the latest/greatest?

**Comment by vmihailenco** [comment]
IMHO the best way is to install airbrake-js using npm (`npm install airbrake-js`) and then add `node_modules/airbrake-js/dist/client.js` file to the assets pipeline. I will consider adding Rails specific example to the repo.

The latest instructions are always at https://github.com/airbrake/airbrake-js/blob/master/README.md . Please use them.

**Comment by gligoran** [comment]
I think (1) is not a good option for production environments, as that file will change through time and may cause problems if they introduce breaking changes.

(2) is more of what I am looking for as well, but again seems to have the same problem as (1). In the article you (@harlantwood) linked, there is a version number 0.3, but modifying that to 0.4.3 (the latest version according to commit 7cb665648eeb8971d6e3b89f51762718e7cf85cd), gets you a 404, the same as 0.4.2. It seems the latest version in there is 0.3.12.

**Comment by arronmabrey** [comment]
I was also looking for a decent solution to this problem, I ended up using https://rails-assets.org/.

I added to my `Gemfile`

```ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-airbrake-js-client'
end
```

and then added the following to my `application.js` file 

```js
//= require airbrake-js-client
```

This is the first time I have used https://rails-assets.org/, but I'm pretty happy with it so far.

**Comment by harlantwood** [comment]
Thanks @arronmabrey, that looks like a good flow.

**Comment by arronmabrey** [comment]
@harlantwood :+1:  We are still using it this way, and it has not been a problem in production thus far.

**Comment by harlantwood** [comment]
rails docs including this method are now at: https://github.com/airbrake/airbrake-js/tree/master/examples/rails
