### ISSUE TITLE
Easier setup via CDN

### ISSUE THREAD

**Issue by dandv** [airbrake/airbrake-js#151]
Would it be possible to provide an easy, drop-in setup of the notifiers, similarly to how Google Analytics or Optimizely or Clicky integrate?

I see the advantage of providing an npm lib/bower package, but for quickly starting up, if I could just add a code snippet after setting the key in a global variable, that would be much easier.

Here's how competitor Loggly does it:

https://www.loggly.com/docs/javascript/

Here's how Intercom (which Airbrake uses for support) does it:

https://gist.github.com/jonathanheron/5910535ce7d393193311

**Comment by LandonSchropp** [comment]
:+1: It would be nice to do this in projects that don't use Bower or NPM.

**Comment by hakunin** [comment]
:+1: Agreed

**Comment by zefer** [comment]
Hi @dandv, @LandonSchropp & @hakunin, [airbrake-js is now available on cdnjs](https://cdnjs.com/libraries/airbrake-js) and we've [updated the README](https://github.com/airbrake/airbrake-js/commit/d84b875785ea4fb19a92055c2d45760a017af032). Thanks for getting in touch, I hope this helps.

**Comment by LandonSchropp** [comment]
@zefer Thanks for taking the time to set that up!

**Comment by zefer** [comment]
@LandonSchropp It's a pleasure. Thanks for your input!
