### ISSUE TITLE
Docs say `new AirbrakeClient`, browser says `AirbrakeClient is not defined`

### ISSUE THREAD

**Issue by aaroncraigongithub** [airbrake/airbrake-js#157]
This is in a Rails 4 app.

I did:

```
bower install airbrake-js-client
```

and in `application.js` I added:
```
//= require bower_components/airbrake-js-client/dist/client.js
```

In my Chrome dev tools sources tab I can see 
```
http://localhost:8080/assets/bower_components/airbrake-js-client/dist/client.self.js?body=1
```

And in that file there is no mention of AirbrakeClient.  In fact, in the entire bower package the only references to AirbrakeClient are in the examples.

Am I doing something wrong?

**Comment by vmihailenco** [comment]
Try https://github.com/airbrake/airbrake-js/blob/master/examples/legacy/app.js#L1:

```
var airbrake = new airbrakeJs.Client(...)
```

I will try to make readme cleaner...

**Comment by vmihailenco** [comment]
Hopefully my hint helped.
