### ISSUE TITLE
improve angular example

### ISSUE THREAD

**Issue by domurtag** [airbrake/airbrake-js#161]
The docs suggest the following approach when using airbrake-js in an angular app

````javascript
mod.factory('$exceptionHandler', function ($log, config) {
  airbrake = new airbrakeJs.Client({
    projectId: config.airbrake.projectId,
    projectKey: config.airbrake.key
  });
  airbrake.addFilter(function (notice) {
    notice.context.environment = config.envName;
    return notice;
  });

  return function (exception, cause) {
    $log.error(exception);
    exception.params = {cause: cause};
    airbrake.notify(exception);
  };
});
````

The line:

    exception.params = {cause: cause};

seems like a bad idea, because it will overwrite the request parameters with the cause of the exception. Is there a better place (in the notice XML) to store the cause?

**Comment by vmihailenco** [comment]
AFAIK `params` will be merged, not replaced. If you already have param called `cause` you can use different name in Angular handler, e.g. `exception.params = {angular_cause: cause}`.
