### ISSUE TITLE
Not working in Angular

### ISSUE THREAD

**Issue by zeeshanjan82** [airbrake/airbrake-js#170]
I have configured Airbrake using following settings:
I have defined the airbrakeJs as 
```js
import airbrakeJs from 'airbrake/lib/client';
```
Then I have defined the service as :
```js
app.factory('$exceptionHandler', function ($log) {
  var airbrake = new airbrakeJs({
    projectId: '1234',
    projectKey: 'xxxxxxxxxxxxxxxxxx'
  });
  airbrake.addFilter(function (notice) {
    notice.context.environment = 'production';
    return notice;
  });

  return function (exception, cause) {
    $log.error(exception);
    exception.params = {angular_cause: cause};
    airbrake.notify(exception);
  };
});

```
When I run my angularjs application, I am able to see errors appearing in the Google Chrome Console window but after I refresh the Airbrake.io dashboard for errors on that specific project, I do not find any errors. I am able to raise the test error from Airbrake.io and it works correctly. I am using jspm instead of Require.js or bower.

**Comment by zeeshanjan82** [comment]
Ok I was able to analyze the issue in depth, As the integration step which is mentioned above works well in angularjs but this will register the Airbrake API after the angularjs application has initialized as we are placing the code in the service but what if I would like to track all the errors in my application which have occurred during the boot process of my application which is before the angularjs is even initialized. Also I found that the errors which are returned from the Express.js API such as the HTTP 500 error code errors are not by default logged. Do we have to use any try catch in order to log such errors.

**Comment by burib** [comment]
@zeeshanjan82 for catching http errors, you'll have to register a http interceptor in your angular application.

**Comment by shime** [comment]
@zeeshanjan82 this exception handler service will only catch errors after the application has initialized. in order to catch HTTP errors, you have to register a HTTP interceptor as @burib suggests. 

here is a simple implementation of HTTP interceptor you can use
```javascript
mod.factory('errorInterceptor', function($q){
  return {
    responseError: function (rejection) {
      var airbrake = new airbrakeJs.Client({projectId: 1234, projectKey: 'XXXXX'});
      airbrake.addFilter(function (notice) {
        notice.context.environment = 'production';
        return notice;
      });
      airbrake.notify("HTTP error");
      return $q.reject(rejection);
    }
};

mod.config(["$httpProvider", function($httpProvider){
  $httpProvider.interceptors.push('errorInterceptor');
}]);

```
