### ISSUE TITLE
Wrong main in bower.json

### ISSUE THREAD

**Issue by santervo** [airbrake/airbrake-js#183]
In recent commit bower main was changed to lib/main.js, but the directory name still remains as dist.

https://github.com/airbrake/airbrake-js/blob/master/bower.json#L9

This breaks builds using automated dependency injection tools, such as wiredep.

**Comment by kyrylo** [comment]
We have a PR for this https://github.com/airbrake/airbrake-js/pull/181. Thanks for confirming it affects wiredep!

**Comment by santervo** [comment]
OK! thanks, closing this one
