### ISSUE TITLE
wrap needs to have notice annotations

### ISSUE THREAD

**Issue by gauravagarwalr** [airbrake/airbrake-js#185]
Hi,

I have been trying to figure out from the docs as to how to pass notice annotations to the wrap function. I do not see any API to do this. Please help if I am missing it, or its entirely a missing feature?

**Comment by vmihailenco** [comment]
Hi,

What do you try to achieve? Can you please show an example?

**Comment by gauravagarwalr** [comment]
You can look at the code examples in https://gist.github.com/gauravagarwalr/b6da89564b75196bdf7b .

The code I had earlier (earlier.js) had been changed to the one using notify (later.js). I was looking for a more succinct API as I have described in needed.js. The idea is to be able to control the notice annotations when using the wrap method, which I do not think exists!?

**Comment by vmihailenco** [comment]
Yeah, it is not supported now. But you can try to add global filter:

```
airbrake.addFilter (notice) ->
    notice.environment.nodeEnvironment = NODE_ENV
    return notice
```

**Comment by gauravagarwalr** [comment]
@vmihailenco I see. Thanks!

**Comment by gauravagarwalr** [comment]
So something like:

```
airbrake.addFilter((notice) => {
  notice.environment.nodeEnvironment = NODE_ENV;
  notice.params = {
    currentUser: currentUserParams,
    state: stateParams
  };
  return notice;
});
```

should suffice, I think! Thanks!

PS: I was using ES6 syntax. I think you syntax is from coffeescript?

**Comment by vmihailenco** [comment]
Yeah, that was CoffeeScript.
