### ISSUE TITLE
jQuery Instrumentation Info

### ISSUE THREAD

**Issue by droppedoncaprica** [airbrake/airbrake-js#190]
Hey everyone, 

After wondering what the jQuery instrumentation file in `/dist/instrumentation/jquery.js` was supposed to do, I checked out the tests.  It seems to hook into a few of events such as the jQuery onload event, catching errors inside jQuery events, etc.

Can we get a section in the README outlining how this file should be used, what the benefits are, what exactly it does, etc?  I'm assuming I just load it directly in the browser like you do with the normal Airbrake reporter client, but it would be nice if this info was included in the README.md for future users.

**Comment by vmihailenco** [comment]
jQuery instrumentation is supposed to catch exceptions that occur in jQuery code and report them to Airbrake. There is an example how to setup jQuery intergration - https://github.com/airbrake/airbrake-js/blob/master/examples/legacy/app.js#L1-L4

**Comment by droppedoncaprica** [comment]
Right, but shouldn't this info be included in the README somewhere?  If there's a dedicated section on Angular reporting, I'd imagine we can add a section for jQuery as well (especially since it requires an additional file and setup).

**Comment by vmihailenco** [comment]
You are right, see https://github.com/airbrake/airbrake-js/pull/192

**Comment by droppedoncaprica** [comment]
Sweet, thanks!  I think that'll help out for anyone using jQuery with Airbrake in the future. :+1:
