### ISSUE TITLE
Doesn't respect sourceMappingURL

### ISSUE THREAD

**Issue by jleppert** [airbrake/airbrake-js#191]
I'm having issues with getting source maps to work. Although I've specified a `sourceMappngURL` comment in my file, your service is requesting what I can only assume to be a default.

Here's the URL to the minified file: 

`https://corona-staging.kespry.com/assets/corona/corona-[digest].js`

Note the comment at the bottom of the file: 

`//# sourceMappingURL=/source_maps?digest=[digest]`

However, I see in the logs when I trigger a test error, you are requesting the following map URL:

`2016-02-17T23:57:52.053068+00:00 heroku[router]: at=info method=GET path="/assets/corona/corona-[digest].js.map" host=corona-staging.kespry.com request_id=3672b2d2-e63d-4c8f-bfb7-25e81d2339e9 fwd="23.253.18.229" dyno=web.1 connect=0ms service=19ms status=404 bytes=1979`

We need to use a custom source map URL so we can control who sees our unminified code.

The source map works fine in chrome, FF, etc. and is accessible with the airbrake user-agen as provided by your support. Please advise if I'm doing something wrong, but according to your docs at https://github.com/airbrake/airbrake-js#source-map it should be good.

**Comment by vmihailenco** [comment]
We are going to fix Airbrake backend to download "https://corona-staging.kespry.com/source_maps?digest=[digest]". Currently it tries to download "https://corona-staging.kespry.com/assets/corona/source_maps?digest=[digest]".

**Comment by vmihailenco** [comment]
@jleppert please try again. Should be fixed.
