### ISSUE TITLE
TypeError: Cannot read property 'jquery' of undefined

### ISSUE THREAD

**Issue by pavankumarkatakam** [airbrake/airbrake-js#196]
Hi im using cdn link version 0.5.8 and as mentioned in the examples legacy mode, im getting the above error.

At this [line](https://github.com/airbrake/airbrake-js/blob/master/examples/bower-wiredep/app.js#L3)

**Comment by shime** [comment]
Unfortunately, you can't use instrumentation if you're using a CDN version, because it comes with [another dist file](https://github.com/airbrake/airbrake-js/blob/f2fe33352bc75e45e215f10bf3e518978376a199/dist/instrumentation/jquery.js).

**Comment by zefer** [comment]
@shime What are the pros/cons of including it in the CDN version? It sounds like it would be helpful.

**Comment by shime** [comment]
@vmihailenco is there a way we can include additional file to cdnjs?

**Comment by vmihailenco** [comment]
I don't know, @zefer added cdnjs.
