### ISSUE TITLE
airbrake-js has typeError in it's own code

### ISSUE THREAD

**Issue by curtislinden** [airbrake/airbrake-js#197]
Error Type:
TypeError

Error Message:
TypeError: Uncaught TypeError: Object #<Event> has no method 'match'

The error is coming from this line. e.message is an event in this case.
Not sure what would make e.message an Event

```
      processor = function(e, cb) {
....
       uncaughtExcRe = /^Uncaught\s(.+?):\s.+$/;
         m = msg.match(uncaughtExcRe);

....
```

**Comment by zefer** [comment]
Hi @curtislinden. Thanks for reporting this. Can you please help by sharing:

* The code you have used to integrate airbrake-js
* The airbrake-js version you are using
* Steps to replicate this error you are seeing

**Comment by vmihailenco** [comment]
What is the result of `String(e.message)`? Is that an acceptable fix?
