### ISSUE TITLE
Fix version in notices

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake-js#202]
This is not being processed, we send it as is: https://github.com/airbrake/airbrake-js/blob/0aaf7026a3eb71a7c607a5f4ce557f3080dbbeda/src/client.coffee#L132

**Comment by vmihailenco** [comment]
It is already fixed https://github.com/airbrake/airbrake-js/blob/master/dist/client.js#L177

**Comment by kyrylo** [comment]
Whoops.
