### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by yaplusplus** [airbrake/airbrake-js#207]
Hello!

I'm trying to include **airbrake** into my browserify app bundle. Bundling process ends successfully, but after opening app page I'm getting an error: `Uncaught ReferenceError: global is not defined`.

My code:

```
const AirbrakeClient = require('airbrake-js');

const airbrake = new AirbrakeClient({
  projectId: '123456',
  projectKey: '123456',
  reporter: 'xhr',
  host: 'http://my-errbit-host.com'
});
```

Error occurs in `Client` constructor function in these lines:

```
if ((global.onerror == null) && opts.onerror !== false) {
  global.onerror = this.onerror;
}
```

Earlier I have tested `airbrake-js` on HTML page without bundling via browserify and it works ok. 
Looks like `global` should be `window` in browser environment. How I can achieve this?
Thanks!

**Comment by vmihailenco** [comment]
Closing since this one is old.
