### ISSUE TITLE
Same code for Angular 2

### ISSUE THREAD

**Issue by m5rk** [airbrake/airbrake-js#209]
It'd be awesome to see example code for wiring up the notifier in Angular 2.

**Comment by kyrylo** [comment]
We don't support Angular 2 officially yet, but it's on our roadmap.

**Comment by choopage** [comment]
@kyrylo I'm considering using Airbrake for my Angular2 project. I have a security question to clarify. I saw that we are required to include our Airbrake API key in our javascript. 

Is it safe to include my Airbrake API key in my Client-Side JavaScript (more specifically Angular2)?

**Comment by kyrylo** [comment]
@choopage check out this issue: https://github.com/airbrake/airbrake-js/issues/4

**Comment by choopage** [comment]
Hi @kyrylo Tentative date in mind for publishing the Angular2 support? 
Also appreciate if you could post it in reddit.com/r/angular2 to share this great news with the community when it's out.

**Comment by zefer** [comment]
Hi @choopage, @m5rk. I've been digging into the Angular2 docs and it looks quite simple to add airbrake-js to an Angular2 app, by implementing [Angular2's `ErrorHandler` class](https://angular.io/docs/js/latest/api/core/index/ErrorHandler-class.html). Based on these docs and our existing [Angular1 example](https://github.com/airbrake/airbrake-js#angular), something like below should work. I'm not familiar with Angular2 or TypeScript so you may need to fill in some gaps. Please let us know how you get on!

```ts
class AirbrakeErrorHandler implements ErrorHandler {
  airbrake: airbrakeJs.Client;

  constructor() {
    this.airbrake = new airbrakeJs.Client({
      projectId: 1234,
      projectKey: 'abcd1234'
    });
  }

  handleError(error) {
    airbrake.notify(error);
  }
}

@NgModule({
  providers: [{provide: ErrorHandler, useClass: AirbrakeErrorHandler}]
})

class MyModule {}
```

**Comment by kyrylo** [comment]
Nice work, @zefer!

@choopage any luck with the example code?

**Comment by choopage** [comment]
I didn't manage to try it yet.

**Comment by pacMakaveli** [comment]
@zefer @choopage I can confirm it works, at least in my Ionic app. It shouldn't be any different in an Angular 2 project except for the way you call the client.

Since Ionic is using webpack, I don't have to call `airbrakeJs.Client` .

`app.logger.ts`
``` js
import { ErrorHandler } from '@angular/core';
import * as airbrakeJs from 'airbrake-js';

export class AirbrakeErrorHandler implements ErrorHandler {

  public airbrake: any;

  constructor() {
    this.airbrake = new airbrakeJs({
      projectId: 1234,
      projectKey: ''
    });
  }

  handleError(error: any): void {
    this.airbrake.notify(error);
  }
}
```

`app.module.ts`
``` js
import { NgModule, ErrorHandler } from '@angular/core';

...

import { AirbrakeErrorHandler } from './app.logger';

...

@NgModule({
  declarations: [],

  imports: [
    IonicModule.forRoot()
  ],

  bootstrap: [IonicApp],

  entryComponents: [],
  providers: [
    {
      provide: ErrorHandler,
      useClass: AirbrakeErrorHandler
    }
  ]
})

...

export class AppModule { }
```

Thanks @zefer

**Comment by zefer** [comment]
Thanks very much for sharing that, @pacMakaveli.

**Comment by davorpeic** [comment]
Hi @pacMakaveli any chance you know why ionic2 app can't find the module? 
`Cannot find module 'airbrake-js'.`

I even tried adding it to rollup.config.js but with no luck, I'm using ionic rc.2

thanks

**Comment by darren-rogan** [comment]
I just hit this issue as well, in angular-cli project

**Comment by darren-rogan** [comment]
I had a similar issue with the npm install. I'm running angular-cli (also uses webpack). I switched to the bower install airbrake-js-client.

 Included the script in the build (`"../bower_components/airbrake-js-client/dist/client.min.js"`) in the package.json (abstracts webpack) and then airbrakeJs was bound on the browser window...

So then I can
`this.airbrakeHandler = (<any>window).airbrakeJs;`
and I not have access to airbrake in my logging service. Not pretty but working, should work for ionic as well

**Comment by davorpeic** [comment]
Hey @darren-rogan I managed it to work with ionic2, I included directly local bower script just to be sure it is working before I find out how to include it in the build, but it sends the error.

For some reason I had to rename api end point from /create-notice to /notices, not sure if something changed in their api..

d

**Comment by jessesanders** [comment]
Another approach is to load client.js using the angular-cli.json file by adding it to the scripts array:

```
"scripts": [
                "../node_modules/airbrake-js/dist/client.js",
                "../node_modules/file-saver/FileSaver.js"
            ],
```

Then you can declare the variable and use it:

```
import {ErrorHandler, Injectable} from '@angular/core';

declare var airbrakeJs: any;

@Injectable()
export class AirBrakeErrorHandler implements ErrorHandler {
    airbrake: any;

    constructor() {
        this.airbrake = airbrakeJs.Client({
            projectId: 123,
            projectKey: 'abc'
        });
    }

    handleError(error) {
        this.airbrake.notify(error);
    }
}
```

**Comment by bitgandtter** [comment]
Hello i tries to use @jessesanders code same as the example on the doc for angular2 project with no luck i got the following error:

```
(unknown) Unhandled Promise rejection: this.addReporter is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.addReporter is not a function
    at Object.Client (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (scripts.bundle.js:21), <anonymous>:1:3854)
    at new AirBrakeErrorHandler (main.bundle.js:95)
    at _createClass (vendor.bundle.js:53397)
    at _createProviderInstance$1 (vendor.bundle.js:53372)
    at initNgModule (vendor.bundle.js:53326)
    at new NgModuleRef_ (vendor.bundle.js:54434)
    at createNgModuleRef (vendor.bundle.js:54418)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (vendor.bundle.js:56712)
    at NgModuleFactory_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleFactory_.create (vendor.bundle.js:57707)
    at vendor.bundle.js:48384 TypeError: this.addReporter is not a function
    at Object.Client (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/scripts.bundle.js:21:8), <anonymous>:1:3854)
    at new AirBrakeErrorHandler (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/main.bundle.js:95:36)
    at _createClass (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:53397:26)
    at _createProviderInstance$1 (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:53372:26)
    at initNgModule (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:53326:13)
    at new NgModuleRef_ (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:54434:9)
    at createNgModuleRef (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:54418:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:56712:12)
    at NgModuleFactory_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleFactory_.create (http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:57707:25)
    at http://ubuntu-yasmanycm923361.codeanyapp.com:8080/vendor.bundle.js:48384:61
```

any advice?

**Comment by jessesanders** [comment]
@bitgandtter - That code sample was for pre web pack which is the standard for the CLI now.  It's most likely your issue.  What version of the cli are you using?  You can check with the following command:  `ng -v`

**Comment by bitgandtter** [comment]
@jessesanders the version of angular-cli is 1.2.1 with node version 8.x and angular 4.x

**Comment by jessesanders** [comment]
I took another look at this for you and my last message was wrong.  The example will work with you version of the cli.  First, look at your .angular-cli.json.  Did you add airbrake to the scripts section?

```
"scripts": [
                "../node_modules/airbrake-js/dist/client.js"
            ],
```
If you put a breakpoint in the constructor for AirBrakeErrorHandler, what is the value of airbrakeJs and airbrakeJs.Client?  If either of these are undefined, then it didn't load the library.  

Check your console, are there any errors being reported?  This would give you clues to other potential issues that are preventing it from working.

**Comment by bitgandtter** [comment]
Yes @jessesanders i include the library on the .angular-cli.json as you advice. The console on the browser raise the error i put on my first post when it tries to construct the AirBrakeErrorHandler class and invoke the airbrakeJs.Client constructor

**Comment by jessesanders** [comment]
Based on what you are describing, its not getting the library loaded.  Double check the node_modules folder and make sure that the airbrake package is installed and in the location that you have in your .angular-cli.json file.

**Comment by bitgandtter** [comment]
@jessesanders you can see the project [here](https://codeanywhere.com/s/l/Zwyy8oU2J9NMpfFmY5I2KmcWqqYC4MfVhSdd4Uri2XS6m3gwv9SQW9ErVccYJZ5z)

as far as the .angular-cli.json

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "airbrake"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [
         "../node_modules/airbrake-js/dist/client.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

```

and yes all the code was successfully installed under the node_modules directory
