### ISSUE TITLE
Invalid action: create-notice

### ISSUE THREAD

**Issue by mrksmts** [airbrake/airbrake-js#210]
CodebaseHQ gives a bad request (400) using the action `create-notice`
According to the Airbrake docs this should be the action `notices`

https://airbrake.io/docs/api/#create-notice-v3

**Comment by vmihailenco** [comment]
Airbrake usually gives you more info in the body when it returns "bad request 400". Were you able to save that info?

**Comment by mrksmts** [comment]
Request:
`https://exceptions.codebasehq.com/api/v3/projects/xxxxxx/create-notice?key=xxxxxxxxxxxxxxxxxxxxxxxxx`

Response body:
`{"status":"invalid-controller-or-action"}`


Response Headers:
```
HTTP/1.1 400 Bad Request
Server: nginx/1.8.0
Date: Tue, 13 Sep 2016 10:16:04 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Status: 400 Bad Request
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
X-Request-Id: 044c0c2256ed497a30963064ca545893
X-Runtime: 0.108879
X-Rack-Cache: invalidate, pass

```

**Comment by vmihailenco** [comment]
Okay, so that is custom tool with Airbrake-like API that does not support `create-notice` API. I think we (Airbrake) have nothing to do here.
