### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by marcocaimi** [airbrake/airbrake-js#213]
According to the airbrake api (https://airbrake.io/docs/api/#error-notification-v3) the url form creating notifications should be:
POST https://airbrake.io/api/v3/projects/PROJECT_ID/notices?key=PROJECT_KEY

but the plugin generates url with this format:

POST https://airbrake.io/api/v3/projects/PROJECT_ID/create-notice?key=PROJECT_KEY

which works well with aibrake service but it's not working with other services supporting the api.

**Comment by vmihailenco** [comment]
I forgot to reply, but you can use xhr reporter as workaround:

```
var airbrake = new airbrakeJs({projectId: 1, projectKey: 'abc', reporter: 'xhr'});
```

The default `compat` reporter uses non-compliant but faster API so I think it should remain to be the default.
