### ISSUE TITLE
How use with react?

### ISSUE THREAD

**Issue by BrunoQuaresma** [airbrake/airbrake-js#215]
I dont see how can i use with React.

**Comment by NourSammour** [comment]
+1

**Comment by kyrylo** [comment]
Hey guys, thanks for your question! Have you tried registering our `window.onerror` handler?

It's described in our README: https://github.com/airbrake/airbrake-js#windowonerror

**Comment by kyrylo** [comment]
If you think that the described way is not enough or you have some other suggestions, please ping me. I tested this on a sample React app (todomvc) and it worked for me.
