### ISSUE TITLE
Record error context

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/airbrake-js#218]
Users sometimes ask us to record error context, e.g.

```
mouseover #main-panel
focus #input-abc
type something
click #btn-foo-bar
```

**Comment by joegod** [comment]
Obviously a lot of details to work out here, but definitely see the value of this.

**Comment by stuartmoore1023** [comment]
> Do you offer context of what happpened before a frontend error such as all the AJAX requests and clicks a user did?

https://app.intercom.io/a/apps/75j3bwun/inbox/all/conversations/6973303895

**Comment by joegod** [comment]
I assume JS would be simplest to tackle first?  Is there a relatively easy way to do a breadcrumbs-like feature for the JS notifier (or others)?

https://blog.sentry.io/2016/05/04/breadcrumbs.html

**Comment by vmihailenco** [comment]
So far done for v0.7.0-rc.2
- console.log instrumentation
- XMLHttpRequest
- click and keypress events
- history.pushState

**Comment by vmihailenco** [comment]
Done in v0.7.0 - UI part is still missing.
