### ISSUE TITLE
Missing documentation about Reporters and React-Native

### ISSUE THREAD

**Issue by padupuy** [airbrake/airbrake-js#222]
Hello,

I use your library 0.5.9 in a React-Native project and it works very well :)

Add first, I try to add the minimal configuration to run the Airbrake Client :
```
const config = {
            projectId: CONFIG.ERRBIT.PROJECT_ID,
            projectKey: CONFIG.ERRBIT.PROJECT_KEY,
            host: CONFIG.ERRBIT.HOST
        };
this.airbrake = new airbrakeJs(config);
```
But if you omit to specify an other reporter than jsonp you'll got an error

![capture d ecran 2016-12-16 a 10 43 24](https://cloud.githubusercontent.com/assets/715255/21258280/86236ba4-c37c-11e6-8495-6d2c2496588e.png)

And that's normal, because inside React-Native context, there is no `document` context .

The good configuration is :
```
const config = {
            projectId: CONFIG.ERRBIT.PROJECT_ID,
            projectKey: CONFIG.ERRBIT.PROJECT_KEY,
            host: CONFIG.ERRBIT.HOST,
            reporter: 'xhr'
        };
this.airbrake = new airbrakeJs(config);
```
I hope this comment will help other developers

**Comment by vmihailenco** [comment]
Looks like this is addressed by adding React Native example. Closing.

**Comment by IkerArb** [comment]
Is React Native no longer supported, or why is it no longer included in the examples folder?

**Comment by padupuy** [comment]
@IkerArb it still works but the example was remove from commit https://github.com/airbrake/airbrake-js/commit/f7a6f0e0eb9828254dc0b6712980235fd613f204
I don't know why

**Comment by zefer** [comment]
Hi @IkerArb, @padupuy. React Native is still supported. The example was removed because f7a6f0e made it easier to use Airbrake with React Native; you can follow the [basic usage instructions](https://github.com/airbrake/airbrake-js#basic-usage), no special config required.
