### ISSUE TITLE
Errors not being recorded

### ISSUE THREAD

**Issue by gregthebusker** [airbrake/airbrake-js#229]
I haven't been able to get any errors to send to airbrake with this setup.  I'm just testing locally with webpack, hot reloading, babel, and react.  I've debugged it a bit and it looks like things are getting set up correctly.  I'm seeing the onerror callback firing too, but nothing get reported to airbrake.

Here's my config

```javascript
import airbrakeJs from 'airbrake-js';
let airbrake = new airbrakeJs({
    projectId: 123456,
    projectKey: 'th1sl00k5r4nd0mr1ght',
});

airbrake.addFilter((notice) => {
    notice.context.environment = process.env.NODE_ENV;
    if (window.LogRocket) {
        notice.context.config = {
            logrocket: LogRocket.recordingURL,
        };
    }
    return notice;
});

```

This investigation originally started with not being able to see errors in a production evn.

**Comment by kyrylo** [comment]
I can see you have this line:

```js
notice.context.environment = process.env.NODE_ENV;
```

Does it mean this code is executed by Node.js? If so, we have a node notifier: https://github.com/airbrake/node-airbrake

**Comment by gregthebusker** [comment]
No. It's run in the browser. Webpack will replace that with the correct ENV.

**Comment by sgray** [comment]
@gregthebusker do you see the POST request to Airbrake firing? If so, is it returning an error? 

I tried to recreate your issue by dropping the config you posted into https://github.com/alicoding/react-webpack-babel, and everything worked properly for me. Is there a sample app you could provide to help debug this issue?

**Comment by gregthebusker** [comment]
So I think what was happening was the error was null because it was cross origin.  That caused the airbrake post request to not fire.  See the note on MDN https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by gregthebusker** [comment]
Basically, I think what's happening is the error is often just "Uncaught undefined: Script error."  And airbrake ignores that because it doesn't have all the full stack trace.  I'm still trying to figure out why it wouldn't have the full stack trace in the JS even though I can see it fully when viewing in the console.

Here's the website I'm working on.  https://www.usewheelhouse.com but I don't have an easy way for you to trigger an error.

**Comment by kyrylo** [comment]
Have you tried adding the `crossorigin` attribute? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-crossorigin

**Comment by gregthebusker** [comment]
I was getting some weird side effects from another service that was causing the issue.  Thanks for looking into things.
