### ISSUE TITLE
airbrake-js-client installed using bower returns airbrake-js: error-stack-parser failed Error: Cannot parse given Error object

### ISSUE THREAD

**Issue by pfarrar1** [airbrake/airbrake-js#285]
Using the setup listed here => https://github.com/airbrake/airbrake-js/tree/master/examples/angular

I keep getting the error:

**airbrake-js: error-stack-parser failed Error: Cannot parse given Error object
    at Object.ErrorStackParser$$parse [as parse]** 

bower airbrake-js-client#*      cached https://github.com/airbrake/airbrake-js.git#0.6.0

Errors are being logged in the Airbrake ui but message are not being parsed.

![screen shot 2017-03-07 at 4 37 09 pm](https://cloud.githubusercontent.com/assets/500743/23681388/6f8dcfa2-0354-11e7-8e9e-95673a8236b9.png)

![screen shot 2017-03-07 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/500743/23681389/6f8ea828-0354-11e7-9c6f-4a8d322f454b.png)

**Comment by pfarrar1** [comment]
This also happens when calling airbrake.notify(exception) by default

**Comment by vmihailenco** [comment]
It should be:

```
airbrake.notify({error: new Error('this is a test')});
```

I will make sure to improve error message in next release.
