### ISSUE TITLE
Breaking Angular app: "airbrake-js: error-stack-parser failed Error: Cannot parse given Error object"

### ISSUE THREAD

**Issue by vincentp** [airbrake/airbrake-js#289]
Hi,

I have the following airbrake config file in my angular app:

```
  app.factory('$exceptionHandler', function($log) {

    return function (exception, cause) {

      $log.warn(exception);

      if (!airbrakeEnabled()) return;

      notifyAirbrake({
        error: exception, 
        params: {
          angular_cause: cause
        }
      });
    };
  });

```

Which works fine most of the time.

But for some reason, some errors can't be parsed properly and I get the following error:

>  airbrake-js: error-stack-parser failed Error: Cannot parse given Error object

Here is the full error I could catch from one of our user:

> SOME_URL&items=7 Failed to load resource: the server responded with a status of 500 (java.util.concurrent.ExecutionException: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.SolrServerException: IOException occured when talking to server at: ANOTHER_URL)
> main.min.js?v=1489049334:27 airbrake-js: error-stack-parser failed Error: Cannot parse given 
> Error object
>     at Object.parse (main.min.js?v=1489049334:27)
>     at Client.d [as processor] (main.min.js?v=1489049334:27)
>     at Client.notify (main.min.js?v=1489049334:26)
>     at f (main.min.js?v=1489049334:27)
>     at responseError (main.min.js?v=1489049334:27)
>     at angular.js:16383
>     at m.$eval (angular.js:17682)
>     at m.$digest (angular.js:17495)
>     at m.$apply (angular.js:17790)
>     at l (angular.js:11831)
> d @ main.min.js?v=1489049334:27
> 

The problem is that once it happens, the angular app is broken, the page has to be refreshed to fix it. I will wrap the airbrake notify function in a try catch for now.

**Comment by vmihailenco** [comment]
That is a log mesage, not an exception - https://github.com/airbrake/airbrake-js/blob/v0.6.0/src/processor/stacktracejs.ts#L13. It should not break anything.

**Comment by vmihailenco** [comment]
Also please try latest v0.7.0 - it should provide much better log message.
