### ISSUE TITLE
Add browser support to readme

### ISSUE THREAD

**Issue by markusfalk** [airbrake/airbrake-js#291]
Could please note the browser support of airbrake-js? 

As always it would be interesting to know what IE versions are supported and furthermore which mobile browser versions (Android, iOS, Chrome?)

thanks :)

**Comment by vladat** [comment]
+1

**Comment by vmihailenco** [comment]
We are using error-stack-parser and should support all browsers supported by it - https://github.com/stacktracejs/error-stack-parser#browser-support.
