### ISSUE TITLE
Sourcemaps security

### ISSUE THREAD

**Issue by hakunin** [airbrake/airbrake-js#301]
Hey guys,
we're adding sourcemaps to get better debug info, but we also don't want anyone reading our source code. Currently it doesn't look like anything is in place to prevent that.

That could be solved this way:

1) Let users upload their sourcemaps, look at how Rollbar is doing it, its pretty simple.
https://rollbar.com/docs/source-maps/

2) Request sourcemaps with a secret token in header. 
This means some setup on a CDN to whitelist it, but its most likely easier for you to support.

**Comment by guiferrpereira** [comment]
+1

**Comment by vmihailenco** [comment]
Hi,

It is not mandatory that source maps must contain source code, e.g. https://cdnjs.cloudflare.com/ajax/libs/airbrake-js/0.7.1/client.min.js.map does not contain source code.

>This means some setup on a CDN to whitelist it, but its most likely easier for you to support.

We almost have this done internally, but we are unsure which token to use. I think it should be sha1 of project API key so we don't have to create yet another token and setting for it, but then we should know to which domain(s) Airbrake should send that token...

**Comment by jaredbrown** [comment]
+1

**Comment by somnolentPumpkin** [comment]
+1

**Comment by hakunin** [comment]
@vmihailenco Seems like uploads would actually be more viable as they're pretty straightforward.

**Comment by vmihailenco** [comment]
Handling user uploads in decent way requires quite some work and maintenance if you want to prevent any abuse. I wonder why source maps without source code is not an option?

**Comment by hakunin** [comment]
Its not quite without source code. You still have the minified code and all the names in the sourcemap so the code becomes much more readable once you apply the map.

Its much better than showing the original source, but still if I can whitelist who can grab the map thats even better and I am going to do that.

**Comment by Vanuan** [comment]
Sourcemaps are only downloaded when DevTools is open. So you'd still have unreadable line numbers thus making airbrake useless.

**Comment by Vanuan** [comment]
It's called security by obscurity. You should not rely on the code to be unreadable. There should be no back doors in your app.

**Comment by jpike88** [comment]
@Vanuan Security by obscurity is bad on its own, but it does help in tandem with other security practices. Reverse engineering a fat client becomes harder (every bit helps), and at least your IP gets some protection too.

@vmihailenco 

> We almost have this done internally

It's now November, so I'd like to know if this is done now. It's really important for us to hide our source maps from the public and helps provide peace of mind to our high value customers despite @Vanuan's point.

**Comment by zefer** [comment]
Hi all. Sorry for the delay, here. We're very close to launching a private sourcemap upload feature.

**Comment by Willis0826** [comment]
@zefer I would like to know is the private sourcemap feature available, now ? Thank you.

**Comment by Willis0826** [comment]
I found the private sourcemaps document here : 
https://airbrake.io/docs/features/private-sourcemaps/
Thanks!
