### ISSUE TITLE
Doesn't work with Turbolinks 5

### ISSUE THREAD

**Issue by vitalinfo** [airbrake/airbrake-js#307]
Got exception on pushState from Turbolinks
<img width="1258" alt="screen shot 2017-03-22 at 5 03 59 pm" src="https://cloud.githubusercontent.com/assets/7523182/24204658/d8cd9208-0f21-11e7-886e-a9049e6a9337.png">

**Comment by vmihailenco** [comment]
Thanks for the report - please try v0.8.3

**Comment by vitalinfo** [comment]
Thanks, I'll check and let you know

**Comment by vitalinfo** [comment]
@vmihailenco have you released 0.8.3? I don't see it 
https://rails-assets.org/#/components/airbrake-js-client

**Comment by kyrylo** [comment]
@vitalinfo it might take some time for rails-assets.org to update the version.

**Comment by vmihailenco** [comment]
It should be available https://github.com/airbrake/airbrake-js/tree/v0.8.3

**Comment by vitalinfo** [comment]
@vmihailenco Thanks 👍 
seems it's working
