### ISSUE TITLE
Advise on what to do if window.onerror is already set

### ISSUE THREAD

**Issue by JasonBarnabe** [airbrake/airbrake-js#312]
https://github.com/airbrake/airbrake-js#windowonerror

> By default, the notifier sets up the window.onerror handler if the onerror handler is not already set up. You can manually set it up using the following code:
> var airbrake = new airbrakeJs.Client(...);
> window.onerror = airbrake.onerror;

If I have an `onerror` already set, presumably doing it manually would wipe out my existing handler. Please document what can/should be done in this case.

Would this work?
```js
window.addEventListener('error', airbrake.onerror);
```

Or would I have to do something like
```js
previousErrorHandler = window.onerror;
window.onerror = function(messageOrEvent, source, lineno, colno, error) {
  previousErrorHandler(messageOrEvent, source, lineno, colno, error);
  airbrake.onerror(messageOrEvent, source, lineno, colno, error);
}
```

**Comment by vmihailenco** [comment]
2nd example with `previousErrorHandler` and `window.onerror` looks good. Just make sure you are using latest v0.8.4.

**Comment by JasonBarnabe** [comment]
Thanks for the response. I think other may have the same question so this would be good to document.

**Comment by JasonBarnabe** [comment]
I'm trying:

```js
var airbrake = new airbrakeJs.Client({projectId: 3.1416, projectKey: 'abc123'});
var previousOnError = window.onerror;
window.onerror = function(args) {
  if (previousOnError) {
    previousOnError.apply(arguments);
  }
  airbrake.onerror.apply(arguments);
}
```
Result is `TypeError: airbrake.onerror is undefined`. I have v0.8.3, you say I need v0.8.4, but `Could not find gem 'rails-assets-airbrake-js-client (>= 0.8.4)' in rubygems repository https://rails-assets.org/.`

**Comment by vmihailenco** [comment]
I guess you need to try again when https://rails-assets.org/ is updated... v0.8.4 was released yesterday - https://www.npmjs.com/package/airbrake-js

**Comment by JasonBarnabe** [comment]
This is the first time I'm using it, but Rails Assets seems to get its stuff from bower, and only 0.8.3 is there.

```
jasons-mbp:canadadrugs jason$ bower info airbrake-js-client
bower airbrake-js-client#*  not-cached https://github.com/airbrake/airbrake-js.git#*
bower airbrake-js-client#*     resolve https://github.com/airbrake/airbrake-js.git#*
bower airbrake-js-client#*    download https://github.com/airbrake/airbrake-js/archive/v0.8.3.tar.gz
bower airbrake-js-client#*     extract archive.tar.gz
bower airbrake-js-client#*    resolved https://github.com/airbrake/airbrake-js.git#0.8.3

{
  name: 'airbrake-js-client',
  version: '0.8.3',
  homepage: 'https://github.com/airbrake/airbrake-js',
  authors: [
    'Airbrake'
  ],
  description: 'Notify Airbrake on JavaScript exceptions',
  main: 'dist/client.js',
  ignore: [
    'src/**',
    'test/**',
    'examples/**',
    'package.json',
    'webpack.config.js',
    'karma.conf.js',
    'tsconfig.json',
    'tslint.json',
    '.gitignore',
    '.travis.yml'
  ],
  moduleType: [
    'amd',
    'globals'
  ],
  keywords: [
    'exception',
    'error',
    'airbrake',
    'notifier'
  ],
  license: 'MIT'
}

Available versions:
  - 0.8.3
  - 0.8.2
  - 0.8.1
  - 0.8.0
  - 0.7.1
  - 0.7.0
  - 0.6.0
  - 0.5.9
  - 0.5.8
  - 0.5.7
  - 0.5.6
  - 0.5.5
  - 0.5.4
  - 0.5.3
  - 0.5.2
  - 0.5.1
  - 0.5.0
  - 0.4.3
  - 0.4.2
  - 0.3.12
  - 0.3.11
  - 0.3.10
  - 0.3.9
  - 0.3.8
  - 0.3.7
  - 0.1.1
  - 0.1.0
  - 0.0.1

Show 26 additional prereleases with ‘bower info airbrake-js-client --verbose’
You can request info for a specific version with 'bower info airbrake-js-client#<version>'
```

**Comment by vmihailenco** [comment]
I am very - I forgot to push v0.8.4 tag. Please try again - bower should see new version. Rails Assets is usually updated with some delay.

**Comment by JasonBarnabe** [comment]
OK, I got v0.8.4, thank for you for that. My current code is:

```js
var airbrake = new airbrakeJs.Client({projectId: 12345, projectKey: 'ABC123', onerror: false});
airbrake.addFilter(function(notice) {
  notice.context.environment = "<%= Rails.env %>";
  return notice;
});

var previousOnError = window.onerror;
window.onerror = function(args) {
  if (previousOnError) {
    previousOnError.apply(this, arguments);
  }
  airbrake.onerror.apply(this, arguments);
}
```
However, if I do *not* already have `window.onerror` set, this reports every exception twice. It looks like the `onerror: false` option from #198 does not work.

**Comment by vmihailenco** [comment]
You are right - `onerror: false` option was removed and there is no replacement at the moment. Most likely I will add it back tomorrow.

**Comment by vmihailenco** [comment]
So `onerror: false` was removed, because airbrake-js setups onerror handler when script is loaded, not when client is initialized. So I can't add it back.

>However, if I do not already have window.onerror set, this reports every exception twice

Most likely `previousOnError` is airbrake-js handler too. That could explain why error is reported twice. Can you try to remove that code?

**Comment by JasonBarnabe** [comment]
I have multiple environments and in some there is another error handler and in others there is not. I would prefer to avoid initializing airbrake in different ways between the different environments, if possible.

Could you modify how airbrake handles setting up onerror to be more like my code above, where it can handle an existing onerror handler?

Or alternately provide a way to detect if the airbrake onerror handler has already been set up?

**Comment by vmihailenco** [comment]
>Could you modify how airbrake handles setting up onerror to be more like my code above, where it can handle an existing onerror handler?

Okay, this seems to be the easiest solution.

**Comment by vmihailenco** [comment]
Please try v0.8.5 - I did some manual testing and it seems to work.

**Comment by JasonBarnabe** [comment]
Thanks, will do once it's on rails-assets.org.

**Comment by JasonBarnabe** [comment]
This seems to work correctly now, both when an onerror handler already exists and when it doesn't. Thanks!

**Comment by vmihailenco** [comment]
Thank you!
