### ISSUE TITLE
Idea: report unsuccessful HTTP requests and rejected notices

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/airbrake-js#314]

**Comment by stuartmoore1023** [comment]
+1
https://app.intercom.io/a/apps/75j3bwun/respond/inbox/all/conversations/9661400220

**Comment by vmihailenco** [comment]
This is already done for fetch - https://github.com/airbrake/airbrake-js/blob/master/packages/browser/src/instrumentation/fetch.ts#L36-L38. As for the rejected notices - they can be handled better in Airbrake backend.
