### ISSUE TITLE
Airbrake Webpack TS errors

### ISSUE THREAD

**Issue by carsonwright** [airbrake/airbrake-js#320]
when trying to import airbrake from airbrake-js I get errors for a bunch of sub ts files in the client directory.

**Comment by carsonwright** [comment]
WARNING in ../~/airbrake-js/dist/client.js
Cannot find source file 'webpack:///./src/reporter/jsonp.ts': Error: Cannot resolve 'file' or 'directory' ./webpac
k:///./src/reporter/jsonp.ts in /Users/********/node_modules/airbrake-js/dist

WARNING in ../~/airbrake-js/dist/client.js
Cannot find source file 'webpack:///./src/reporter/node.ts': Error: Cannot resolve 'file' or 'directory' ./webpack
:///./src/reporter/node.ts in /Users/********/node_modules/airbrake-js/dist

WARNING in ../~/airbrake-js/dist/client.js
Cannot find source file 'webpack:///./src/reporter/reporter.ts': Error: Cannot resolve 'file' or 'directory' ./web
pack:///./src/reporter/reporter.ts in /Users/********/node_modules/airbrake-js/dist

WARNING in ../~/airbrake-js/dist/client.js
Cannot find source file 'webpack:///./src/reporter/xhr.ts': Error: Cannot resolve 'file' or 'directory' ./webpack:
///./src/reporter/xhr.ts in /Users/********/node_modules/airbrake-js/dist

**Comment by vmihailenco** [comment]
There is no .ts files in airbrake-js distribution. Looks like you import airbrake-js incorrectly.

**Comment by gimenete** [comment]
I had the same issue and solved it with this in the webpack configuration:

```javascript
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          path.join(nodeModulesPath, 'airbrake-js')
        ]
      },
```
