### ISSUE TITLE
Prevent repeated error reporting

### ISSUE THREAD

**Issue by JasonBarnabe** [airbrake/airbrake-js#321]
I've seen some cases where the the client reports the same error 100 times in a row in the same second. This exceeds our plan's limit by itself.

Can the JS client be modified to only report the same* error once per page load?

\* same = same error message and backtrace?

**Comment by vmihailenco** [comment]
You can write filter for this:

```
var lastNotice;
airbrake.addFilter(function(notice) {
  // Following line requires some work to compare notices.
  if (notice == lastNotice) {
    return null;
  }
  return notice;
});
```

**Comment by xavhan** [comment]
Is a debouncing strategy better for this kind of use ?

**Comment by xavhan** [comment]
thanks for you work @vmihailenco , i'll try this asap.

**Comment by vmihailenco** [comment]
It is not released yet - I need to add tests and do some manual testing as well...
