### ISSUE TITLE
Error when using with React-Native

### ISSUE THREAD

**Issue by ibussieres** [airbrake/airbrake-js#335]
```
const airbrakeJs = require("airbrake-js");
const airbrake = new airbrakeJs({
  projectId: 1,
  projectKey: "key",
  reporter: "xhr"
});
```

![image](https://cloud.githubusercontent.com/assets/422296/26206615/51f3df26-3bb3-11e7-93e6-b919c872dcde.png)

**Comment by vmihailenco** [comment]
Please try v0.9.0. I did not test it with iOS, but it works with Android.

**Comment by ibussieres** [comment]
Working fine on iOS with 0.9.0. Thanks !
