### ISSUE TITLE
Add option to not listen to window.onerror

### ISSUE THREAD

**Issue by vdhpieter** [airbrake/airbrake-js#339]
It is possible to add the option for not listening to window.onerror? It was added in #199 but deleted afterwards (see https://github.com/airbrake/airbrake-js/issues/312#issuecomment-293333830)
Now we get a lot of errors because of extensions but there are not really usefull. It is also not an option to add filters for every error we want to be notified about.

This bug makes this tool kinda useless for us...

**Comment by vmihailenco** [comment]
It was removed, because `window.onerror` handler is setup when script is loaded, not when notifier is created. But I think we can add an option to ignore errors from `window.onerror`.

**Comment by vmihailenco** [comment]
I've just added `ignoreWindowError` option to v0.9.2. In existing app you could try to add a filter:

```
airbrake.addFilter(function(notice) {
    if (notice.context.windowError) {
        return null;
    }
    return notice;
});
```

**Comment by vdhpieter** [comment]
Thank you for the quick support!
