### ISSUE TITLE
"Converting circular structure to JSON" in debounce filter

### ISSUE THREAD

**Issue by vihai** [airbrake/airbrake-js#341]
Hello,

I'm using airbrake in a ExtJS application and I noticed I was losing many error reports. I found that the debounce filter was silently failing due to ```JSON.stringify(notice)``` throwing a:

```
Uncaught TypeError: Converting circular structure to JSON
```

Most probably it was one argument in one of the history entries in notice.

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in v0.9.3
