### ISSUE TITLE
Ignore errors come from safari-extension://

### ISSUE THREAD

**Issue by JasonBarnabe** [airbrake/airbrake-js#343]
Like #315, these errors come from extensions.

> Message	undefined is not an object (evaluating 'divPos.x.toString')
> URL	https://www.mysite.com/my/url
> File	safari-extension://com.wondershare.safari.itubestudio-KN9QEHBS7D/c54610c5/Core.js:225
> User agent Safari 10.1.1
> Backtrace 
> safari-extension://com.wondershare.safari.itubestudio-KN9QEHBS7D/c54610c5/Core.js:225:35 in adjustAttachButtonPos
> safari-extension://com.wondershare.safari.itubestudio-KN9QEHBS7D/c54610c5/Core.js:546:106 in onShowElement
> my/js/file:15:10022 in nrWrapper

**Comment by vmihailenco** [comment]
I *think* that if you install airbrake-js into your extension the URL will be the same...

**Comment by vmihailenco** [comment]
Closing since this would break airbrake-js used in safari extensions to report errors.
