### ISSUE TITLE
cdn for airbrake notifier js

### ISSUE THREAD

**Issue by vijayj** [airbrake/airbrake-js#35]
Hi,
We are a JS app and we have decided to use the airbrake-js for our error notifications. I was following the docs and it seems like the cdn source location for notifier.js [<script defer src="https://ssljscdn.airbrake.io/notifier-v0.2.js"  ] is incorrect. 

``` javascript
<script>
  window.Airbrake = [];
  window.Airbrake.try = function(fn) { try { fn() } catch(er) { window.Airbrake.push(er); } };
</script>
<script defer src="https://ssljscdn.airbrake.io/notifier-v0.2.js"  
        data-airbrake-project-id="1234"
        data-airbrake-project-key="abcd"
        data-airbrake-project-environment-name="production"></script>
```

Can you let us know what the right cdn is ? Thanks

**Comment by dandv** [comment]
There is no longer a mention of a CDN in the README, it seems.

**Comment by joaomilho** [comment]
Yeah, no mention on the README... :/

**Comment by zefer** [comment]
Hi @joaomilho @dandv [airbrake-js is now available on cdnjs](https://cdnjs.com/libraries/airbrake-js) and we've [updated the README](https://github.com/airbrake/airbrake-js/commit/d84b875785ea4fb19a92055c2d45760a017af032). I hope this helps!
