### ISSUE TITLE
Custom SourceMap URL problem

### ISSUE THREAD

**Issue by PidginEnemy** [airbrake/airbrake-js#352]
Hi, i tried to add custom source map url and i hope to see right path to file when error occured.
I have one bundle, that's why i typed like this in my app:
```javascript
airbrakeClient.addFilter((notice) => {
      notice.context.sourceMaps = {
        '*': `${window.location.origin}/assets/app-bundle.js.map`
      }
}
```
In airbrake interface in file field i see this - http://prntscr.com/g0glsm
This is link to bundle, not to original file.
In context field i see this: http://prntscr.com/g0gmmv

What could be wrong ?
Thanks.

**Comment by vmihailenco** [comment]
Can you check the value of `context.sourceMapErrors`? It should contain something like

```
  "sourceMapErrors": {
    "https://your-server.com/bundler.js": "can't find source map URL"
  },
```
