### ISSUE TITLE
v0.9.5 doesn't work for Node(express)

### ISSUE THREAD

**Issue by aquajach** [airbrake/airbrake-js#357]
@vmihailenco what's the reason behind to make such a change? https://github.com/airbrake/airbrake-js/commit/9645209359d3055c85aa145e6157d9c06277bc98#diff-c36e9b38e2cb8f53b4bc0ba690e79236

Changing from `setTimeout` To `window.setTimeout` makes node unable to use v0.9.5 in backend.

**Comment by vmihailenco** [comment]
That was done, because on Node `setTimeout` returns `Timer` and Typescript emits a warning that types don't match. Will fix in v0.9.6
