### ISSUE TITLE
Add an Angular 4 configuration example

### ISSUE THREAD

**Issue by cwayfinder** [airbrake/airbrake-js#360]
The one provided for Angular 2 is not actual anymore. I was looking through GitHub issues for a proper example but didn't find anything 100% working.

I would appreciate if you provided an actual example of `AirbrakeErrorHandler` for Angular 4.

**Comment by vmihailenco** [comment]
I've update example with more precise instructions, but overall Angular 4 has the same `ErrorHandler` interface.

**Comment by cwayfinder** [comment]
Thanks!
