### ISSUE TITLE
The process may terminate before the errors are sent to airbrake

### ISSUE THREAD

**Issue by Bastes** [airbrake/airbrake-js#365]
So, here's the catch, on a nodejs process:

```javascript
try {
  throw new Error('woopsie daisy')
} catch(err) {
  // this will attempt to notify airbrake
  airbrake.notify(err);
  // but we throw immediately afterwards, before the airbrake notification has time to terminate
  throw err;
}
```

It's not just hand-made catching and notifying:

```javascript
var startApp = function() {
  // This will throw if the document has no head tag.
  throw new Error('woopsie again, daisy')
}
startApp = airbrake.wrap(startApp);

// yup, wrap will not have time to sent the notification before the re-thrown error terminates the process
startApp();

// guess what? call won't do either
airbrake.call(startApp);
```

Now, we can handle that with a `try { ... } catch (...) { ... }` block and a `setTimeout(...)`:
```javascript
try {
  airbrake.call(startApp);
}
catch (err) {
  // providing enough time before throwing again can help
  setTimeout(() => { throw err }, 10000)
}
```

But it feels a bit clunky.

**Comment by Bastes** [comment]
I guess this problem doesn't happen on a webpage because the webpage doesn't necessarily terminate when an exception is thrown ^^°

**Comment by vmihailenco** [comment]
I am aware of the problem, but I don't know how to fix it so it works in browsers and Node.js (or even in different Node.js versions). Do you have any ideas?

**Comment by Bastes** [comment]
Hehe, that's a tricky one for sure ^^° but if you're sending a query to airbrake asychronously, there's most likely a promise happening somewhere to which you could tie a callaback to execute when the promise resolves - or rejects.

If you can point me to the place where the actual sending happens, I may give a suggestion (or maybe even better: a PR) to improve it.

**Comment by vmihailenco** [comment]
`airbrake.notify` returns a Promise, but I don't see how you can wait until it is resolved without `async/await` support which is only available in latest browsers/Node.js.
- wrap function https://github.com/airbrake/airbrake-js/blob/master/src/client.ts#L180
- custom Promise implementation https://github.com/airbrake/airbrake-js/blob/master/src/promise.ts
- uncaught exception handler https://github.com/airbrake/airbrake-js/blob/master/src/instrumentation/historian.ts#L41-L45

**Comment by Bastes** [comment]
It all depends on wether the promise actually awaits for the query to finish to resolve, or if it's just there to be a promise (which would be an anti-pattern, kind of a fake promise, pardon the pun ^^).

I'm going to look into the code you pointed. Thanks ^^

**Comment by Bastes** [comment]
@vmihailenco actually, what would help would be the source of the "notify" function ; that's the one that would show wether it awaits for the query to complete to resolve or not.

**Comment by Bastes** [comment]
Ah, got it. Looking into it right now...

**Comment by Bastes** [comment]
Ok, sorry for the long pause, I got sidetracked for a few days ^^°

So, as far as I can tell, the "reporters" are handling the errors being sent to airbrake, and most likely it's the nodeReporter that's handling the ones sent by node (I know, that sounds even more obvious now I'm writing it ^^°).

The nodeReporter is using https://github.com/request/request to do the heavy lifting ; request is provided a callback to handle the results... and I think that's where something goes wrong ^^

I'm still trying to figure that out ; I'll let you know if I stumble upon something ^^

**Comment by vmihailenco** [comment]
This is "fixed" by not re-throwing exception in uncaughtHandler - https://github.com/airbrake/airbrake-js/commit/e994ecb9496bccc8f68b2a571cf5153eec6559ba.

**Comment by Bastes** [comment]
Thanks, I'll let you know if I encounter the same problem again ^^d
