### ISSUE TITLE
Using 'airbrake-js' for React Native crashes the app

### ISSUE THREAD

**Issue by swarna-sathya** [airbrake/airbrake-js#374]
To use airbrake-js for reporting crashes in React Native code, I ran ```$npm install airbrake-js```
Following the instructions in [React Documentation](https://github.com/airbrake/airbrake-js/tree/master/examples/react) leads to a crash - as seen in the screenshot attached.

Trial and error while debugging, I removed all the code, except an import statement:
```import AirbrakeClient from 'airbrake-js'```
This is also leading to the same crash.

![whatsapp image 2017-12-13 at 10 30 38 am](https://user-images.githubusercontent.com/18487471/33922576-b3440516-dff1-11e7-85b9-50f4e359247b.jpeg)

Could not find any documentation related to this error. I wonder if it is anything related to the version of libraries.

The following are the react-related dependencies in my package.json:

```"dependencies": {
    "airbrake-js": "^0.9.9",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.3",
    "react-native-checkbox": "^1.1.0",
    "react-native-device-log": "0.0.17",
    "react-native-dialogs": "0.0.19",
    "react-native-signature-capture": "^0.4.5",
    "react-native-simple-radio-button": "^2.5.0-alpha.1",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "^1.0.0-beta.9",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-persist": "^4.5.0",
    "redux-promise-middleware": "^4.2.0",
    "redux-thunk": "^2.2.0"
  }
```

Can you please help me fix it?

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed in v1.0.0
