### ISSUE TITLE
Historian window.fetch error in node

### ISSUE THREAD

**Issue by guitarama** [airbrake/airbrake-js#375]
This is the recommended lib since node-airbrake deprecated.  But Historian code wrapping fetch throws an error in node (I'm using 8.9.1) that "window is not defined".
I would like to submit a PR to check for typeof(window) but the project doesn't seem to build for me due to:
```
ERROR in /src/promise.ts(1,13)
TS1148: Cannot use imports, exports, or module augmentations when '--module' is 'none'.
```

If anyone else runs into it, I am currently using airbrake-js 0.8.8 as a workaround.

**Comment by vmihailenco** [comment]
How do you build it?

**Comment by guitarama** [comment]
just about as the readme prescribes:
1. `npm i`
2. `npm run build`

running `npm run test` step also throws the webpack error then proceeds to run karma on the previous build it seems.

**Comment by vmihailenco** [comment]
Please try master branch - the problem should be fixed.
