### ISSUE TITLE
Support for async code?

### ISSUE THREAD

**Issue by coryc5** [airbrake/airbrake-js#379]
Hello,

We have a rather large JS app with a fair amount of async code. As far as I can tell, there is no support for catching an error like this without wrapping the async callback in a wrap function.

```
function setupAirbrake() {
  const airbrake = new Airbrake({
    projectId: process.env.AIRBRAKE_PROJECT_ID,
    projectKey: process.env.AIRBRAKE_PROJECT_KEY
  });

  airbrake.addFilter(function filterAirbrakeNotice (notice) {
    console.log(notice)

    return notice;
  });

  return airbrake;
};

const airbrake = setupAirbrake();

airbrake.call(() => {
  const p = new Promise((resolve) => {
    return resolve()
  })

  // will cause an error that is not caught by airbrake
  p.then(result => null.ok)
});

airbrake.call(() => {
  // also will not get caught
  setTimeout(() => null.ok2, 0);
});
```

While wrapping such async callbacks is an option, converting a large app with lots of these callbacks is going to be tedious, and there is going to be a large opportunity for callbacks to overlooked and missed. It would be nice if we could just call airbrake in one place and count on it to catch all errors that occur from that point forward, regardless of the context they occur in. 

Unless this is already possible and I've missed it?

Thanks.

**Comment by vmihailenco** [comment]
Probably the best option is to instrument `Promise` class, but it is complicated since AFAIK there is no single `Promise` implementation on all platforms... What platform do you use and how Promise is defined?

**Comment by coryc5** [comment]
We are using the browser-native promise implementation.
