### ISSUE TITLE
No support for changing the max jsonify length

### ISSUE THREAD

**Issue by wesleytodd** [airbrake/airbrake-js#381]
The method support accepting a max length, but none of the implementations allow passing it.  Is this intentional?  Or simply an oversight?

See:

- [jsonfiy alert method](https://github.com/airbrake/airbrake-js/blob/c2b6feede435ff62733861df78ccaafeedc7fd11/src/jsonify_notice.ts#L6)
- [xhr implementation](https://github.com/airbrake/airbrake-js/blob/f67fc0b94544341c8350acd6fd806766f64b1731/src/reporter/xhr.ts#L19)

**Comment by vmihailenco** [comment]
It is intentional because the limit is the same for all Airbrake plans.

**Comment by wesleytodd** [comment]
Ok. My recommendation would be to figure out a way to truncate it within the module then.  Just implementing the client has resulted in errors being logged back to airbrake from the airbrake client.  Logs like:

```
Error: airbrake-js: cannot jsonify notice (length=8223860 maxLength=64000)
```

I think the client should implement some truncation method if your own platform does not support the messages your official client sends.  I can take a look at what a PR for this would look like if you think it would be acceptable to truncate.

**Comment by kyrylo** [comment]
We already truncate notices here: https://github.com/airbrake/airbrake-js/blob/master/src/jsonify_notice.ts

Seems like there was some condition which prevented truncation. One way to work around it is to use filters to strip out unknown information.

**Comment by vmihailenco** [comment]
My guess is that `notice.errors` takes most of the space, because it is not truncated at the moment. This can and should be improved, but still `8223860` is a lot and it would be nice to understand how such big error was created in first place...

**Comment by vmihailenco** [comment]
Please v1.0.3 - it should truncate notice more aggressively. Also it it still fails logged error should have `err.params` attribute with some hints about the notice and why truncation failed.

**Comment by wesleytodd** [comment]
We did update before opening this issue.  I don't know what is causing such a big error output, trust me I wish I did :).  We have not found a replication technique for this error, so we are relying on the module to report correctly.  Maybe it should report context when it reaches this situation and show as much of the error as it can fit?

**Comment by vmihailenco** [comment]
v1.0.3 was released today so you need to update again.

>Maybe it should report context when it reaches this situation and show as much of the error as it can fit?

That is what truncation tries to achieve. Probably it should be even more aggressive, but let's try v1.0.3 first.

**Comment by wesleytodd** [comment]
Oh, yeah maybe that was `1.0.2` we updated to.  I will update and see what that gets us.  But I think my recommendation still stands, it should report as much as it can, and not just swallow the user application error.
