### ISSUE TITLE
Error on React Native iOS

### ISSUE THREAD

**Issue by dhanson358** [airbrake/airbrake-js#382]
Looks similar to previously-reported #335 .

I am following this example:
https://github.com/airbrake/airbrake-js/tree/master/examples/react

Version is 1.0.1.

![image](https://user-images.githubusercontent.com/545837/34943286-abf048d6-f9c0-11e7-954b-7887d95747f3.png)

Any ideas?

**Comment by vmihailenco** [comment]
Hopefully should be fixed in v1.0.2 - thanks for the report.
