### ISSUE TITLE
How to wrap `debug` instead of console.log ?

### ISSUE THREAD

**Issue by Overdrivr** [airbrake/airbrake-js#386]
I'm using the [`debug`](https://www.npmjs.com/package/debug) module to manage logs in my NodeJS application.

Since airbreakjs only wraps `console.log` calls, I am not getting logs with my reported errors, just a stack trace that is not very helpful without context ( I believe that `debug` module directly writes to stdout or stderr, which is why nothing shows up)

How can I have airbreak report my debug logs along with the error in this situation ?

Or maybe airbreak does not support reporting the log along with the error ?

**Comment by vmihailenco** [comment]
We already patch `console` to report logs with errors - https://github.com/airbrake/airbrake-js/blob/master/src/instrumentation/historian.ts#L199-L219. I think we should add something similar for debug module...
