### ISSUE TITLE
Invalid calling object 

### ISSUE THREAD

**Issue by tbnovaes** [airbrake/airbrake-js#387]
NPM version: 5.6.0
Node version: 9.4.0
OS: Windows
Browser: IE 11

Issue:
My application started crashing on IE11, with an error of `Invalid Calling Object`, after speding some time debugging, I figured out that what was causing the problem was any airbreak-js version of 1.0.*

Solution:
Downgrading it to 0.9.9 fixed my issue with IE11

**Comment by hugoarpin** [comment]
Same problem here.
Caused by line 193 in airbrake-js/src/instrumentation/historian.ts
I think this is the problem:
```javascript
add = document.addEventListener;
```
Seems like IE does not allow to create these kind of aliases.

**Comment by vmihailenco** [comment]
Thanks for debugging it - I've reverted that change in v1.0.4

**Comment by tbnovaes** [comment]
Thank you @vmihailenco

**Comment by hugoarpin** [comment]
Thank you, really fast response!
Are you in charge of the gem on https://rails-assets.org/#/components/airbrake-js-client?
I won't be able to update to v1.0.4 until the gem is updated.

**Comment by vmihailenco** [comment]
Yes, I believe it is automatically updated with some delay.
