### ISSUE TITLE
Airbrake uncaught exception handler should not swallow errors

### ISSUE THREAD

**Issue by RandomSeeded** [airbrake/airbrake-js#389]
Heyo, I see that the following change was made: https://github.com/airbrake/airbrake-js/commit/e994ecb9496bccc8f68b2a571cf5153eec6559ba, presumably in order to handle https://github.com/airbrake/airbrake-js/issues/365

This really does not work well with node scripts; the uncaught exception handler will swallow any errors unless the caller has its own `uncaughtException` handler, causing the script to hang instead of crash. This change therefore requires every script which requires `airbrake-js` (or requires a file which requires `airbrake-js`, etc.) to have its own uncaught exception handler just to re-throw errors a la 

```
process.on('uncaughtException', e => {
  throw e;
});
```

which is really not ideal. It seems like it would be better to have `historian.notify` return a promise and then re-throw the error after the resolution of that promise

**Comment by RandomSeeded** [comment]
OK on further thought re-throwing the error is also not great; in that situation you might not actually trigger the other uncaught exception handlers with the re-thrown error, in which case you'd actually crash when the exception should have been properly handled.

So probably the best bet here would be to only add the `uncaughtException` handler conditionally, aka allow a flag at initialization which prevents the adding of the handler. If I made a PR for this would y'all be amenable to this approach?

**Comment by vmihailenco** [comment]
What about adding `console.log(e)` with some helpful message? Would that be enough?
