### ISSUE TITLE
"Can't find variable:document" when import airbrake-js on react-native

### ISSUE THREAD

**Issue by wjy617** [airbrake/airbrake-js#396]
![screenshot](https://user-images.githubusercontent.com/7648203/36014044-9afb261c-0d1c-11e8-8003-f666c85d5d37.png)

Anyone has come across such issue and how to fix it? Thanks

**Comment by vmihailenco** [comment]
Please try v1.0.5

**Comment by wjy617** [comment]
It works! Thanks Vladimir
