### ISSUE TITLE
Private sourcemap making unneeded request to server

### ISSUE THREAD

**Issue by alonquil** [airbrake/airbrake-js#413]
I'm trying to follow the instructions [here](https://airbrake.io/docs/features/private-sourcemaps/) to upload a private sourcemap.
My minified source file is in `assets/application-123.js` and the sourcemap is in `assets/maps/application-987.js.map`. The last line of the source file is
`//# sourceMappingURL=/assets/maps/application-987.js.map`.
So I run the curl command copied from that link (with my own id and token):
```
curl https://airbrake.io/api/v4/projects/<id>/sourcemaps \
  -X POST \
  -H 'Authorization: Bearer <token>' \
  -F file=@/assets/maps/application-987.js.map \
  -F name="http://localhost:3000/assets/application-123.js"
```
It seems to work and returns an id. But when I view a freshly raised error on airbrake, the folllowing is shown in the Context panel:
```
"sourceMapErrors": {
   "http://localhost:3000/assets/application-123.js": "Get http://localhost:3000/assets/application-123.map: dial tcp 127.0.0.1:3000: connect: connection refused"
},
```

It looks as though Airbrake is trying for some reason to request `assets/application-123.map`, which obviously isn't working. Why does it need to request anything when I have already uploaded the map?  And why would it be looking for `application-123.map` when that doesn't match either of the filenames I provided?

**Comment by vmihailenco** [comment]
It requires time to debug this properly, but first thing I would try is to change `name="http://localhost/assets/application-123.js"` to `name="http://localhost:3000/assets/application-123.js"` and try to send error again.

**Comment by vmihailenco** [comment]
@alonquil did you try updated file name? is it working?

**Comment by alonquil** [comment]
Hi, thanks for the reply. Actually I tried this already, no luck :(

**Comment by vmihailenco** [comment]
Okay you need to make 2 changes. First specify sourcemap for the file in notice context:

```
notice.context["sourceMaps"]["http://localhost:3000/assets/application-123.js"] = "http://localhost:3000/assets/application-123.js.map"
```

Then upload sourcemap to Airbrake under its name:

```
curl https://airbrake.io/api/v4/projects/<id>/sourcemaps \
  -X POST \
  -H 'Authorization: Bearer <token>' \
  -F file=@/assets/maps/application-123.js.map \
  -F name="http://localhost:3000/assets/application-123.js.map"
```

See https://github.com/airbrake/airbrake-js#source-map for explanation.

**Comment by alonquil** [comment]
Just to be clear, the minified source and the sourcemap have different basenames and locations: `assets/application-123.js` and `assets/maps/application-987.js.map`.

So I think your first line should rather be ``notice.context["sourceMaps"]["http://localhost:3000/assets/application-123.js"] = "http://localhost:3000/assets/maps/application-987.js.map"``, is that right? Could you explain why this line is necessary? I thought Airbrake should learn the location of the map file from the `sourceMappingURL` directive at the end of the source file? Also, the documentation for Private Sourcemaps doesn't mention this line at all.

I realise now the 'name' param should match the map file rather than the source. I had misunderstood this before.

But, with both of these changes, I am still getting the exact same issue. Any ideas...?

**Comment by vmihailenco** [comment]
This works as following:
- Airbrake encounters filename http://localhost:3000/assets/application-123.js
- It is supposed to download it to extract sourcemap location, but it can't
- It looks into `notice.context["sourceMaps"]` in case you manually associated sourcemap for the file
- From sourceMaps Airbrake know that sourcemap is located at http://localhost:3000/assets/maps/application-987.js.map, but it can't download it too
- It checks if you manually uploaded that file to Airbrake using private sourcemap feature

>I am still getting the exact same issue. Any ideas...?

What error do you get now? Can you mail me link to the error to vlad@airbrake.io?

**Comment by sorokinvj** [comment]
hey guys, sorry for reopening this, but I do everything explained in the docs to upload my private source maps, but in the end I don't see "usedSourceMaps" property in context,

Though if I trigger error manually by 
```
window.onerror("Test Error: web.50f78adae21082803b18.js", "https://.../web.50f78adae21082803b18.js", 123, 1)
```
then I do have error:
```
  "sourceMapErrors": {
    "https://.../web.50f78adae21082803b18.js": "sourcemap: no source for given line and column"
  }
```
All names, filenames and patterns are correctly set. Sourcemaps upoaded, I see them when do API request
