### ISSUE TITLE
Filter all errors except those manually sent

### ISSUE THREAD

**Issue by noctivityinc** [airbrake/airbrake-js#420]
We are seeing almost all is errors coming from third party scripts.  We would like to only send errors that we specifically do Airbrake.notify with. How can we do this?

**Comment by vmihailenco** [comment]
You can try `{ignoreWindowError: true}` option - https://github.com/airbrake/airbrake-js#windowonerror.

v1.1.0 also has `unhandledrejection` handler, but we don't option to disable it yet. Which version do you use?

**Comment by noctivityinc** [comment]
0.9.8. The ruby gem hasn’t been updated with 1.0 yet
  

  
  

  
  
>
