### ISSUE TITLE
airbrake.addReporter is not a function

### ISSUE THREAD

**Issue by paulewog** [airbrake/airbrake-js#423]
Previously, I was adding a custom airbrake reporter by doing:

```
var AirbrakeClient = require('airbrake-js');
var airbrake = new AirbrakeClient({ projectId: 12345, projectKey: 'hi there' });
airbrake.addReporter(...);
```

In airbrake 1.1.0, this seems to be failing... was that intended? :)

**Comment by vmihailenco** [comment]
Yes, it is intended. What are you doing in custom reporter? Is there any way to achieve the same without custom reporter?

**Comment by paulewog** [comment]
It looks like it is still referenced on the readme :)

We were using it to log out the error locally in addition to sending it to airbrake.  I haven't looked for a different way to do it yet. :)

**Comment by paulewog** [comment]
Thanks, by the way! Forgot to get back to you. :)

**Comment by vmihailenco** [comment]
Thank *you*.

**Comment by hale** [comment]
@paulewog is a changelog maintained for each new release? I didn't realize this feature was removed -- thanks.
