### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by simonwacker** [airbrake/airbrake-js#424]
How can this library be used behind a proxy?

**Comment by zefer** [comment]
Hi @simonwacker. You can override the host when you initialise the library, this will tell it to send errors to your proxy. https://github.com/airbrake/airbrake-js/blob/master/src/client.ts#L54

For example: `var airbrake = new airbrakeJs.Client({projectId: 1, projectKey: 'abc', host: 'https://myproxy.com'});`

**Comment by simonwacker** [comment]
Dear @zefer, that sadly won't do in my case because I don't have control over the proxy. I run Node.js on a Server behind a proxy and need it to report errors to Airbrake. So, for example, in case `client.ts` uses `reporter/node.ts`, I need to be able to configure the http proxy settings of [request](https://github.com/request/request). Best, Simon.

**Comment by vmihailenco** [comment]
I am thinking about adding new option:

```
var baseRequest = request.defaults({
  proxy: 'your proxy goes here',
})

var airbrake = new Client({
  request: baseRequest,
});
```

and then airbrake-js will used provided request wrapper. What do you think?

**Comment by simonwacker** [comment]
That would be perfect! :)
