### ISSUE TITLE
Filtering HTMLDocument.<anonymous>

### ISSUE THREAD

**Issue by odlp** [airbrake/airbrake-js#430]
We're getting errors which have `HTMLDocument.<anonymous>` in the backtrace:

![js-error-html-anon](https://user-images.githubusercontent.com/4125410/40498267-763e980c-5f76-11e8-9416-52b340e27ec9.png)

I'm aware one can use `airbrake.addFilter` to remove these, but my question is whether this case should be added to the default ignore filter which already strips `<anonymous>` errors?

https://github.com/airbrake/airbrake-js/blob/c5e55f13c407b73125170e004662321ec1cbb459/src/filter/ignore.ts#L18-L20

Is this an error which is reported regularly across Airbrake customers? And if so, is there a way of checking if they ever have actionable data / fixable causes? Or is it just noise?

**Comment by vmihailenco** [comment]
AFAIK such errors are throwed in browser addons and you can't do anything to fix them. I guess `HTMLDocument.<anonymous>` is another example of such error. I would investigate further before ignoring it globally...
