### ISSUE TITLE
Couldn't import AirbrakeClient

### ISSUE THREAD

**Issue by muk-ai** [airbrake/airbrake-js#441]
I wrote the code with reference to the following, an error will occur.
https://github.com/airbrake/airbrake-js/tree/master/examples/angular-2

> import AirbrakeClient from 'airbrake-js';

```
error TS1192: Module ''airbrake-js'' has no default export.
```

then I changed the code.

> import { Client } from 'airbrake-js';

```
error TS2305: Module ''airbrake-js'' has no exported member 'Client'.
error TS2497: Module ''airbrake-js'' resolves to a non-module entity and cannot be imported using this construct.
```

Am I doing something wrong?

airbrake-js: 1.3.1
typescript: 2.6.2

**Comment by vmihailenco** [comment]
I just tried `import AirbrakeClient from 'airbrake-js'` and it worked for me. So I guess it is specific to your setup. Can you try `var AirbrakeClient = require('airbrake-js')`?

**Comment by muk-ai** [comment]
Thank you for your quick reply.

I could solve this problem, but I had to specify `allowSyntheticDefaultImports: true` option in tsconfig.json.

I guess there is no `export default` in `.d.ts`, but I am not familiar with typescript.
https://github.com/airbrake/airbrake-js/blob/master/dist/client.d.ts

**Comment by vmihailenco** [comment]
I think I've fixed this in airbrake-js, but most likely you want to enable `esModuleInterop` too - see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by vmihailenco** [comment]
Please try v1.4.0

**Comment by muk-ai** [comment]
Thank you for quick fix!!!

but **my** tsconfig.json still needed that option (`esModuleInterop` or `allowSyntheticDefaultImports`)
Without these options, `Module ''airbrake-js'' has no default export` displayed

airbrake-js: 1.4.0
typescript: 2.7.2

**Comment by muk-ai** [comment]
@vmihailenco 
What do you think of this? https://github.com/airbrake/airbrake-js/pull/444
