### ISSUE TITLE
Sourcemaps not found

### ISSUE THREAD

**Issue by philippotto** [airbrake/airbrake-js#445]
Hi there,

we use airbrake for minified javascript which references the corresponding sourcemaps via
`//# sourceMappingURL=main.js.map` (as emitted by webpack). However,  the sourcemaps are not found on airbrake.io. In the context of an error, this is shown:

```
 "sourceMapErrors": {
    "https://webknossos.brain.mpg.de/assets/bundle/main.js%3Fnocache=ddcfd829f626b5e2191c979e8aa7087c14fbdea4": "http.Get url=\"https://webknossos.brain.mpg.de/assets/bundle/main.js%3Fnocache=ddcfd829f626b5e2191c979e8aa7087c14fbdea4\": got 404 Not Found, expected 200 OK",
    "https://webknossos.brain.mpg.de/assets/bundle/vendors~main.js%3Fnocache=ddcfd829f626b5e2191c979e8aa7087c14fbdea4": "http.Get url=\"https://webknossos.brain.mpg.de/assets/bundle/vendors~main.js%3Fnocache=ddcfd829f626b5e2191c979e8aa7087c14fbdea4\": got 404 Not Found, expected 200 OK"
  },
```

The source map for `https://webknossos.brain.mpg.de/assets/bundle/main.js` is at `https://webknossos.brain.mpg.de/assets/bundle/main.js.map` (as the last line of `main.js` also indicates). However, the source map url is not even tried according to the error message? Maybe the cache busting (`main.js?nocache=commithash`) breaks something?

**Comment by vmihailenco** [comment]
Looks like `?` in `main.js?nocache=commithash` is encoded as `%3F` for some reason. Can you check why? E.g. if file in error backtrace is properly encoded or not.

**Comment by vmihailenco** [comment]
I wonder what browser you are using? `create-notice` endpoint is supposed to be used when `XMLHttpRequest` and `fetch` are undefined, which is true for really ancient browsers. Also what airbrake-js version you are using?

>Should I file this somewhere else?

No, this repo is fine.

**Comment by philippotto** [comment]
I'm using Chrome 65, but you are right: the airbrake-js version was outdated. I updated it to the newest one. Now, the `notices` endpoint is used. However, the sourcemaps error (including `%3F`) is still there:

```
"sourceMapErrors": {
    "https://updateairbrake.webknossos.xyz/assets/bundle/vendors~main.js%3Fnocache=dc9b10e6f2cc545b18925575bbb637af9102bd69": "http.Get url=\"https://updateairbrake.webknossos.xyz/assets/bundle/vendors~main.js%3Fnocache=dc9b10e6f2cc545b18925575bbb637af9102bd69\": got 404 Not Found, expected 200 OK"
  },
```
However, the request payload uses the proper formatting using `?`.

**Comment by vmihailenco** [comment]
Well, at some point `?` gets escaped and that is the problem. Can you send me airbrake.io UI link to the error to vlad@airbrake.io?
