### ISSUE TITLE
Airbrake notify context environment defaulting to "development"

### ISSUE THREAD

**Issue by kz363** [airbrake/airbrake-js#450]
As of https://github.com/airbrake/airbrake-js/issues/438, it seems like the Airbrake client is hard-coding `notice.context.environment` to `development` in all cases. This is causing all errors to be reported as coming from a development environment even when Node is running in a production environment.

The innocuous change as follows:
https://github.com/airbrake/airbrake-js/blob/e2eaca8204c14b4bdc75fbc8b31c336965218b15/src/filter/node.ts#L29-L31

And after Webpack compiles it:
https://github.com/airbrake/airbrake-js/blob/e2eaca8204c14b4bdc75fbc8b31c336965218b15/dist/client.js#L1471-L1473

**Comment by vmihailenco** [comment]
Thanks for the report - it should be fixed in v1.4.2
