### ISSUE TITLE
Couldn't find enough finder patterns (found 0) in historian.ts:118

### ISSUE THREAD

**Issue by Htarlov** [airbrake/airbrake-js#452]
I pretty often get notification about error "Couldn't find enough finder patterns (found 0)"

Airbrake version used: 1.4.2
File: historian.ts:118

Always from browser Chrome 67 or 66 (both desktop and Android)

Backtrace:
```
webpack://airbrakeJs.Client/./src/historian.ts:118 in notify
webpack://airbrakeJs.Client/./src/historian.ts:104 in notifyNotifiers
webpack://airbrakeJs.Client/./src/historian.ts:137 in notify
webpack://airbrakeJs.Client/./src/historian.ts:39 in apply
```

**Comment by vmihailenco** [comment]
Do you use jsqrcode? Did you see https://github.com/LazarSoft/jsqrcode/issues/59?

**Comment by Htarlov** [comment]
I see we import it for some part that is not currently in use but we don't run it (as that functionality is hidden). Will try to comment out import of that one and check if it helps. Thanks.
