### ISSUE TITLE
"Can't resolve 'fs' " when importing airbrake-js in React's ErrorBoundary component.

### ISSUE THREAD

**Issue by cis-ankity** [airbrake/airbrake-js#453]
Module not found: Error: Can't resolve 'fs'  '/windows/frontend/node_modules/request/lib'

 Module not found: Error: Can't resolve 'net' in '/windows/frontend/node_modules/forever-agent'

**Comment by xylude** [comment]
I'm also having this issue when building for production - I'm assuming it's because [this line](https://github.com/airbrake/airbrake-js/blob/master/src/client.ts#L20) is importing a file that references the native node request library and webpack is trying to build that in to the bundle.

**Comment by vmihailenco** [comment]
I guess you mean your app bundle you are building using Webpack. In that case I guess the solution is to use `externals` option in your webpack config as in https://github.com/airbrake/airbrake-js/blob/master/webpack.config.js#L27-L31. I am happy to fix this on airbrake-js side but I don't know how.

**Comment by xylude** [comment]
Thanks @vmihailenco that worked. This still might be an issue with people using `create-react-app` though, since they hide the webpack configs from the devs. Not sure on that, but it's probably worth checking out.

**Comment by cis-ankity** [comment]
Thanks @vmihailenco, I've mentioned the fs, net commands in web pack config files external plugins and it worked.
