### ISSUE TITLE
Backtrace with webpack URLs & integration github

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake-js#454]
I'm not totally sure if this issue should be poste here (It's related to the website airbrake.io).

Here is a line in my backtrace 
```
webpack:///app/javascript/backoffice/components/pages/crud/Index.vue:223
```
(it's in production and has been "extracted" thanks to sourcemaps)

The corresponding github repo is integrated on the project and `app/javascript/backoffice/components/pages/crud/Index.vue:223` is the correct path in the repo

Is is normal that there is no link in the backtrace to github ?
Is there a way to make it happen ?

**Comment by vmihailenco** [comment]
I will create internal airbrake issue since this is not related to airbrake-js. I will ask to update this one once it is fixed.

**Comment by vmihailenco** [comment]
This seems to be fixed in our private repo.
