### ISSUE TITLE
Problem with Angular 6+ builds with versions >1.2.0

### ISSUE THREAD

**Issue by pleinonen** [airbrake/airbrake-js#457]
Following error can be seen when building application:

```
WARNING in ./node_modules/airbrake-js/dist/client.js
Module not found: Error: Can't resolve 'os' in 'node_modules/airbrake-js/dist'
```

Problem was introduced in airbrake-js version 1.3.0 and same thing happens with latest. Version 1.2.0 is the last version which is working for me. My app is an Angular 6.1 app and I use AngularCLI tooling to build the app. Any idea what could be wrong here?

**Comment by vmihailenco** [comment]
I guess you need to add following line into your webpack config - https://github.com/airbrake/airbrake-js/blob/master/webpack.config.js#L27-L37
