### ISSUE TITLE
Consider remove request dependency on Node.js

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/airbrake-js#465]

**Comment by chrisnoreikis** [comment]
Is this library intended for use in the context of a browser?  I've wanted to use airbrake-js in front end applications before, but have avoided it due to the node dependency

**Comment by vmihailenco** [comment]
airbrake-js works in web browser - there are lots of [examples](https://github.com/airbrake/airbrake-js/tree/master/examples)

**Comment by geminiyellow** [comment]
👍 waiting

**Comment by sithmel** [comment]
airbrake-js works in the browser but its size is huge. This is mostly because of request: it requires to polyfill many node objects (buffers for example).
Just to give some context: airbrake alone accounts for 60% of my bundle size.

**Comment by vmihailenco** [comment]
You don't need request in browser context - there are reporters that use [XHR](https://github.com/airbrake/airbrake-js/blob/master/src/reporter/xhr.ts), and [fetch](https://github.com/airbrake/airbrake-js/blob/master/src/reporter/fetch.ts), and [jsonp](https://github.com/airbrake/airbrake-js/blob/master/src/reporter/jsonp.ts). Reporter is automatically chosen based on what is available - https://github.com/airbrake/airbrake-js/blob/master/src/reporter/reporter.ts#L22-L34

**Comment by sithmel** [comment]
It doesn't matter whether is used or not. As soon as request is in your dependency tree, it will be included in the bundle.

**Comment by vmihailenco** [comment]
Most [examples](https://github.com/airbrake/airbrake-js/tree/master/examples) work correctly (or used to work correctly at the moment of testing) without `request` package installed. Webpack also has `externals` option which allows you to exclude anything from the bundle.

**Comment by sithmel** [comment]
I added a proposal here: https://github.com/airbrake/airbrake-js/pull/475

**Comment by sithmel** [comment]
This looks ok in airbrake-js 1.5.0 beta :+1: 
thanks a lot!
