### ISSUE TITLE
Need to send notification when airbrake-js is already sending it?

### ISSUE THREAD

**Issue by emipc** [airbrake/airbrake-js#471]
I was looking at the React example (https://github.com/airbrake/airbrake-js/tree/master/examples/react) and I'm wondering why do we need to do an `airbrake.notify()` there when the code from airbrake-js is listening for the `window.onerror` event and is already sending the notification there?

Won't the notification be sent twice?

**Comment by vmihailenco** [comment]
Can't say for sure - I think it depends on your setup. Errors reported from window.error hook have `context.windowError = true` set so you check that attribute to see if there are duplicates.

**Comment by emipc** [comment]
I've seen there is an option to ignore errors reported by window.onerror with `ignoreWindowError` (false by default). I guess you need to set it to true in case you want to notify errors in your codebase?
