### ISSUE TITLE
Getting MaxListenersExceededWarning when running tests

### ISSUE THREAD

**Issue by emipc** [airbrake/airbrake-js#473]
I'm getting this warning several times when running our test suite while importing `airbrake-js` as a dependency:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```

After checking the airbrake code, I've realised that you're listening for the `uncaughtException` and `unhandledRejection` events thru `process.on()`. I removed this code and it was not throwing the warnings anymore.

Maybe `airbrake-js` should remove these event listeners before adding new ones?

**Comment by vmihailenco** [comment]
Please try v1.4.9. I don't fully understand how modern JS works, but the idea is that there should be exactly one instance of `Historian` class and therefore only one listener that is never removed. Historian singletone is defined [here](https://github.com/airbrake/airbrake-js/blob/master/src/historian.ts#L94-L99) - let me know if you spot any mistakes.

There are also listeners created for each client which can be removed using [client.close](https://github.com/airbrake/airbrake-js/blob/master/src/client.ts#L109-L114). But looks like there are no problems with those.
