### ISSUE TITLE
Send user id when exception is thrown

### ISSUE THREAD

**Issue by jaredsohn** [airbrake/airbrake-js#477]
I am looking to send back a user id when an exception gets thrown so I know which user encountered an error. It looks like `setErrorDefaults` would do this but that it had been removed for reasons that are unclear to me. Is there another way to do this?

Context: this is within a browser exception when js errors exist outside of my code.

**Comment by vmihailenco** [comment]
Take a look at [filters](https://github.com/airbrake/airbrake-js#filtering-errors) -  they allow to set arbitrary information on the notice. For user information I suggest to use `context.user`:

```
context.user = {
  id: 123,
  name: "User Name",
  username: "nickname",
  email: "mail@me.com"
}
```

**Comment by jaredsohn** [comment]
Thanks. I only skimmed the README and didn't see that there were two uses for filters.
