### ISSUE TITLE
Historian and error filtering

### ISSUE THREAD

**Issue by sithmel** [airbrake/airbrake-js#478]
I am using airbrake-js inside my bundle. My application is a small widget that can be incorporated in many different pages (even third parties).
I am filtering out all errors fired by others analysing the "backtrace" array. Wherever I find the name of my script in one of the items, I consider the error to be relevant. I discard it otherwise.

This filtering works with a notable exception: whenever the error is propagated from a "fetch" or a "XMLHttpRequest.open" the backtrace contains a reference to the version of those functions contained in the Historian module.And this is included in my bundle.

Is there a way to disable historian? It really doesn't add a lot of value for us.

**Comment by vmihailenco** [comment]
Hi,

I've tried to address this in https://github.com/airbrake/airbrake-js/pull/481. Basically you should be able to control what is instrumented using client options like this:

```
var airbrake = new airbrakeJs.Client({
  projectId: 1,
  projectKey: 'REPLACE_ME',
  environment: 'production',
  instrumentation: {
    console: false,
    fetch: false,
    xhr: false,
  }
});
```

I am still not quite happy with it so leaving it open until next week in case there are better ideas.
