### ISSUE TITLE
opts.environment overwritten by nodeFilter

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake-js#486]
nodeFilter is pushed after the filter on environment
https://github.com/airbrake/airbrake-js/blob/1c3a3bae2fc80fa93f48c95b8c4735e9756a547b/src/client.ts#L71-L76

so this
https://github.com/airbrake/airbrake-js/blob/1c3a3bae2fc80fa93f48c95b8c4735e9756a547b/src/filter/node.ts#L30
is overriding the custom environment given in `new AirbrakeClient({ environment })`

I'm forced to add a new filter with the same behavior as 
https://github.com/airbrake/airbrake-js/blob/1c3a3bae2fc80fa93f48c95b8c4735e9756a547b/src/client.ts#L71-L76

**Comment by vmihailenco** [comment]
Probably already fixed in master since I don't see such line in https://github.com/airbrake/airbrake-js/blob/master/src/filter/node.ts

**Comment by MathieuDerelle** [comment]
you're right, https://github.com/airbrake/airbrake-js/commit/fbfbef1ce2ab01dc29c23fea9fd46db4fcf21346 fixed it on master

when is the next release ?

**Comment by vmihailenco** [comment]
I hope to push something today, but it will be beta.
