### ISSUE TITLE
Source map with explicit URL will not work

### ISSUE THREAD

**Issue by deecewan** [airbrake/airbrake-js#491]
I'm working on a react-native project, so I have no publicly available JS. However, I am uploading the source maps to S3, and attaching the correct `//# sourceMappingURL=` to the bottom of the JS bundle.

However, every time I do this, in airbrake.io, I see:

![image](https://user-images.githubusercontent.com/4755785/48992768-64ddc500-f185-11e8-8db4-78e9e0cc10ba.png)

I'm not sure why it's worrying about that. The JS file includes the sourcemap URL at the bottom of it. Is there any reason this isn't working, or is there some other known issue with this?

**Comment by vmihailenco** [comment]
There are no details except the error message which says that Airbrake expects absolute URL with scheme and hostname. Did you try to provide such URL?

**Comment by deecewan** [comment]
yes. I provided a fully qualified name inside of the `//# sourceMappingURL` comment.

I eventually solved this by explicitly telling airbrake where the maps are during my build step, using the sourcemaps context option.

**Comment by vmihailenco** [comment]
Okay, glad you solved it. Closing.
