### ISSUE TITLE
When elapsed time is 0ms, makeMiddleware produces an error

### ISSUE THREAD

**Issue by penngrove** [airbrake/airbrake-js#493]
I added:

app.use(makeMiddleware(AIRBRAKE))

in my express app, but some requests are fast enough to be 0ms which causes the Airbrake API to return the following error on flush:

can not report routes stats Error: route stat: sum <= 0
    at /Users/benoitm/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/http_req/fetch.ts:49:27
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by vmihailenco** [comment]
Perhaps we should treat 0 as 0.1ms. That is slightly more accurate than 0ms, We could also use `process.hrtime()` on Node.js.
