### ISSUE TITLE
`sourceMapErrors` when using airbrake-js with node

### ISSUE THREAD

**Issue by ptolemybarnes** [airbrake/airbrake-js#500]
I am using `airbrake-js` version `1.4.7` in an express application and calling `airbrake.notify`. In the 'context' section of the error report, I see the following:

```
"sourceMapErrors": {
    "/opt/app/app/routes/proxy.js": "absolute URL expected",
    "/opt/app/node_modules/request/request.js": "absolute URL expected",
    "_http_client.js": "absolute URL expected",
    "events.js": "absolute URL expected",
    "internal/process/next_tick.js": "absolute URL expected",
    "internal/streams/destroy.js": "absolute URL expected"
  }
```

I think this might be because the airbrake client is looking for source maps to provide a better stacktrace, and it's failing because it hasn't been configured with a URL at which to find them. Surely source maps are a purely client-side thing, though? So it is redundant to look for them in a server-side environment. Initially I found this message quite confusing as it seemed to imply a problem with the code, rather than airbrake.

Perhaps `airbrake-js` should detect that it's running in a server-side environment and not look for source maps. Would you accept a PR for this?

**Comment by vmihailenco** [comment]
Those errors are set on the Airbrake servers and they should not affect anything. In order to remove those errors we need to update Airbrake backend and I am not sure what can be done in airbrake-js.

How do you suggest to detect server side environment?  Is something like that enough?

```
(typeof process !== 'undefined') &&
(typeof process.versions.node !== 'undefined')
```
