### ISSUE TITLE
include src in npm package

### ISSUE THREAD

**Issue by dreyks** [airbrake/airbrake-js#502]
noticed that the lib started to bundle fetch polyfills and according to https://github.com/airbrake/airbrake-js/pull/476/files#r219801170 this was done on purpose for people that don't use webpack

could you then add `src` folder to the npm distribution for people that do use webpack and do not want additional dependencies?

also the corss-fetch could at least be peerDependency

**Comment by vmihailenco** [comment]
I already struggle to support every JS flavor existing in the wild and including src only makes this situation 10 times worse. Because 99% of users do not know how to use it and the rest 1% will do all the smart and dirty tricks you can imagine. That is  just a guess though.

**Comment by vmihailenco** [comment]
Next major v2.0 will be shipped with sources and different bundle formats (iife, cjs, esm). Hopefully it will not bring too much chaos.

**Comment by dreyks** [comment]
thx. will give it a try when it lands
