### ISSUE TITLE
Cannot find module 'cross-fetch' from 'client.js'

### ISSUE THREAD

**Issue by btimo** [airbrake/airbrake-js#506]
The latest PR introduced a breaking change in the library: [#505](https://github.com/airbrake/airbrake-js/pull/505)
You shouldn't change the way a library is used/installed with a minor version.

And some good comments after this other issue was closed: [!501](https://github.com/airbrake/airbrake-js/issues/501)

**Comment by penngrove** [comment]
Adding cross-fetch to your project will make it work, but should be added by airbrake-js automatically

**Comment by vmihailenco** [comment]
cross-fetch in in peer dependencies so you can install version of your choice (or not install anything at all) -- https://github.com/airbrake/airbrake-js/blob/master/package.json#L17-L19. Perhaps that is too confusing but only time will tell.

**Comment by btimo** [comment]
What is confusing is the change in a minor version 😉

**Comment by vmihailenco** [comment]
v1.6 was released days ago and it did not work for some use cases. v1.6,1 fixed that but broke something else. v1.6.2 is the first version that seems to work for most of the users even though it is backwards incompatible with 1.6.1 and 1.6.0.

**Comment by eaviles** [comment]
Sharing the same comment as @btimo as this broke the contract from 1.5. Also, I don't think it's OK not installing cross-fetch at all as it was still making our service to crash.

**Comment by ron23** [comment]
I also think it's not the right approach. And it should have been a major version change.
Moreover, I don't see why a polyfill is needed as a peer-dependency (see https://github.com/airbrake/airbrake-js/issues/502)

Lastly, v1.6.2 doesn't work for me on Node env (Without manually installing cross-fetch).
Why do I need to include cross-fetch if I don't use it explicitly? That's very odd. Also I tend to look at my package.json file to see which libraries a project is using. Having a library that isn't directly required is odd. I'm also pretty sure scripts that check for unused dependencies will fail to detect the usage.

**Comment by badunk** [comment]
The problem here is that it falls on node and it's a breaking change.
