### ISSUE TITLE
Gem needs updating for rails

### ISSUE THREAD

**Issue by noctivityinc** [airbrake/airbrake-js#507]
Just tried to update the gem for version 1.6.1 and its stuck on 1.5.0.

**Comment by vmihailenco** [comment]
Latest version is v1.6.2 and it is on npm and cdnjs. I guess you are using bower? I am not sure what must be done to update it. We have the v1.6.2 git tag.

**Comment by noctivityinc** [comment]
Nope just using bundler with the ruby gem listed in your readme.

**Comment by noctivityinc** [comment]
Any update on this?  It's still pointing to the old gem 1.5.0

**Comment by vmihailenco** [comment]
rails-assets are using Bower to find latest version of the package. Bower should automatically pick up new version whenever git tag is created, e.g. https://github.com/airbrake/airbrake-js/tree/v1.6.3. Most of the time Bower works, but sometimes it does not. And I can't find out why...

**Comment by vmihailenco** [comment]
I am trying to figure out why bower is not updated. Meanwhile you can try solution described in https://ricostacruz.com/til/npm-in-rails

**Comment by noctivityinc** [comment]
I dont want to add another package manager to my app just for this one thing.  Can I simply download the airbrake js file and add it to my app until you fix this?

**Comment by noctivityinc** [comment]
Hi-

Why did you close this?  It's still broken:

```
Bundler attempted to update rails-assets-airbrake-js-client but its version stayed the same
Bundle updated!
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

12:35 PM ~/projects/dmv/dmvcs (feature/yogov_cs_bar) => gem list | grep airbrake
airbrake (7.4.0)
airbrake-ruby (2.12.0)
rails-assets-airbrake-js-client (1.5.0)
```

**Comment by noctivityinc** [comment]
If you check the source of the gem, it's clear it's still on 1.5.0

https://rails-assets.org/#/?query=airbrake

**Comment by sgray** [comment]
Hi, @noctivityinc. Sorry for the hassle with rails-assets.org. [It appears](https://rails-assets.org/status) that they're no longer actively maintaining that project. I've created #523 with examples using the asset pipeline and Webpacker. The simplest method of including airbrake-js in a Rails app is to follow the first option and include the compiled airbrake-js source in your `vendor` directory. Please let me know if anything else comes up.

**Comment by noctivityinc** [comment]
Yeah that's what I ended up doing.  Thank you.
