### ISSUE TITLE
Notification severity option is not being passed.

### ISSUE THREAD

**Issue by Ggpsv** [airbrake/airbrake-js#516]
Hi! We're using airbrake and `airbrake-js@1.6.3` in our project. We've been trying to set a custom severity for a particular type of error following the instructions from the README on `severity`.

```js
airbrake.notify({
    error,
    params: { info },
    context: {
        severity: 'critical'
    }
});
```

As we test the errors thrown, the `severity` option is not being passed. All errors are going out with the default severity `error`, and a little bit of debugging tells me that this is being emitted by Historian's `onerror` listener instead. Is there something else to this that we may be missing? The docs don't tell much otherwise. 

The alternative that I've found is adding a filter where we override the severity if it is a `windowError`.
```js
context: {
    severity: notice.context.windowError ? 'critical' : notice.context.severity,
    environment
}
```

We're not a fan of this approach since it looses the granularity of being able to specify the severity at the `notify()` level. 

For context, our client configuration is simple, it only passes the required `projectId` and `projectKey` options. Additionally, we only have 1 filter where we check if the current environment is a development environment, for which don't notify. 

Thank you!

**Comment by vmihailenco** [comment]
I've just tried the latest version and it works as expected. Try to upgrade and create small program that reproduces the problem.
