### ISSUE TITLE
AirbrakeClient opt reporter changed from string to function

### ISSUE THREAD

**Issue by rinu** [airbrake/airbrake-js#517]
I recently upgraded from 1.5.x to 1.6.x and as a result I get errors in airbrake-js.
`reporter` used to be defined as a string for one of `AirbrakeClient`'s options. Now it's expected to be a function. If left as a string, it will cause a TypeError on notify. There should be a check for a string for better backwards compatibility.

https://github.com/airbrake/airbrake-js/blob/master/src/client.ts#L214

**Comment by vmihailenco** [comment]
Check for string and do what?

**Comment by rinu** [comment]
I would throw a warning to console and then act as if reporter is undefined.
