### ISSUE TITLE
Feature request: Support client library server proxy

### ISSUE THREAD

**Issue by andrii-melnyk-ring** [airbrake/airbrake-js#525]
We have restriction that secrets should not be exposed to the front-end application.

Airbrake js client library supports host option, but it will replace only part of url and properties "projectId" and "projectKey" are required, which makes no sense in this case.

What do you think about to support additional optional property "apiProxy"?
If it would be set, then this value will completely replace url "`https://api.airbrake.io/api/v3/projects/<projectId>/notices?key=<apiKey>`".
It would be responsibility of the server endpoint to proxy client error to the airbrake service.

I can implement this functionality and open PR.

**Comment by vmihailenco** [comment]
Can't you use dummy values there?

Generally I don't mind if the change will be small, self-contained and tested.

**Comment by andrii-melnyk-ring** [comment]
I thought about it, but endpoint will break convention. With host option it will look like:
`https://host/api/v1/client-errors/api/v3/projects/1/notices?key=1`

And in case of library update if it will affect airbrake api version, we should rename entire endpoint instead of just bump endpoint version and update implementation.

So additional parameter it would be better solution. I've already made implementation, writing tests.

**Comment by andrii-melnyk-ring** [comment]
Hi @vmihailenco, can you take a look into PR and add comment? Maybe you'll find that some stuff should be removed from PR.
