### ISSUE TITLE
Empty response from routes-stats returns empty body -- throws error

### ISSUE THREAD

**Issue by egdelwonk** [airbrake/airbrake-js#532]
We're using airbrake-js with Express. 

It looks like the POST request to routes-stats returns an empty response.

e.g.

```shell
curl --request POST \
  --url 'https://api.airbrake.io/api/v5/projects/<project id>/routes-stats?key=<key>' \
  --header 'content-type: application/json' \
  --data '{
  "environment": "development",
  "routes":[
    {
      "method": "GET",
       "route": "*",
       "statusCode": 200, 
       "time":"1970-01-01T00:00:00.000Z",
       "count": 1,
       "sum": 0.371977,
       "sumsq": 0.138366888529
    }
  ]
}'
```

Airbrake has a peer-dependency of cross-fetch. When a request is returned, and the status code is between 200 and 300, cross-fetch via airbrake-js will attempt to parse the response as JSON. But if this API response is empty, the parsing fails and throws an error message:

```shell
can not report routes stats { FetchError: invalid json response body at https://api.airbrake.io/api/v5/projects/<project id>/routes-stats?key=<key> reason: Unexpected end of JSON input
    at /dev/frontend/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://api.airbrake.io/api/v5/projects/<project id>/routes-stats?key=<key> reason: Unexpected end of JSON input',
  type: 'invalid-json' }
```

I've created a simple test script to recreate the error that does not use `airbrake-js` directly, and it seems to isolate the issue with `cross-fetch`, however the issue would be with how airbrake-js is using cross-fetch (fetch) in the package (http_req/fetch.ts)

```javascript
const fetch = require("cross-fetch");

const data = {
  environment: "development",
  routes: [
    {
      method: "GET",
      route: "*",
      statusCode: 200,
      time: "1970-01-01T00:00:00.000Z",
      count: 4,
      sum: 6.268870000000001,
      sumsq: 30.844375986766003,
    },
  ],
};
fetch(
  "https://api.airbrake.io/api/v5/projects/<project id>/routes-stats?key=<key>",
  {
    method: "POST",
    body: JSON.stringify(data),
  }
)
  .then(resp => {
    console.log("content-length", resp.headers.get("content-length")); // will be 0 for this route

    // This will throw an error if content-length is 0
    if (resp.status >= 200 && resp.status < 300) {
      return resp.json().then(json => {
        return { json };
      });
    }

    return null;
  })
  .catch(err => {
    console.error("err", err);
  });
```

So it looks like there would need to be a conditional added to https://github.com/airbrake/airbrake-js/blob/master/src/http_req/fetch.ts#L40 to handle an empty response, or to patch the airbrake api to return an appropriate response body. 

This error only started to show up in the last couple of days from what we can tell, so i'm curious if anything has changed on the endpoint's response recently.

Happy to submit a PR if this is indeed unexpected behavior. 

Cheers!

**Comment by egdelwonk** [comment]
On an e-mail thread with Morgan @ Airbrake support, they had mentioned that route-stats is a private beta feature, so there might need to either have some feature flag checking, or a configuration option for the AirbrakeClient constructor to opt into experimental features.

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed on the server side
