### ISSUE TITLE
request method always 'GET' in history when fetch being called with a Request object

### ISSUE THREAD

**Issue by andresattler** [airbrake/airbrake-js#540]
We recently discovered that all our error notices have only `GET` request in the history of an error notice.  

In our api we create [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) objects that we set the argument for `fetch()`.

The problem is  that currently, `airbrake-js` is aware of the type of the first param of fetch to be a `string` or a `Request` but it did not handle the setting of the method when the first argument of fetch was from type `Request`

**Comment by vmihailenco** [comment]
Closed by https://github.com/airbrake/airbrake-js/pull/544
