### ISSUE TITLE
Can not report routes stats Error: time="1970-01-01 00:50:00 +0000 UTC" is too far in the past

### ISSUE THREAD

**Issue by Hirurg103** [airbrake/airbrake-js#542]
After I upgraded aibrake js for my express app from `v0.9.8` to `v1.6.6` I started to see the following errors in my logs:

```
can not report routes stats Error: time="1970-01-01 00:50:00 +0000 UTC" is too far in the past
./source/node_modules/airbrake-js/dist/client.js:1979:27
at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Is this related to time configuration on my server some way?

How can I fix this error?

**Comment by Hirurg103** [comment]
Hi @vladimiry thank you for the quick fix 👍 I appreciate that very much!

**Comment by vladimiry** [comment]
Thanks go to @vmihailenco :+1:
