### ISSUE TITLE
Empty Response when Notifying of Error

### ISSUE THREAD

**Issue by aedryan** [airbrake/airbrake-js#546]
Using version: 1.6.7

Intermittently I get an empty response when sending an error notification and I can't figure out why.  I can see in [the API documentation](https://airbrake.io/docs/api/#create-notice-v3) that there are some error response codes possible due to bad requests, rate limits, or too-large requests but what I'm seeing is no response at all.  Chrome gives me the dreaded `ERR_EMPTY_RESPONSE` and when I try the same request with a curl I get `curl: (52) Empty reply from server`.  I have been unable to find any documentation that would explain why this occurs.  

I say this occurs intermittently because sometimes, it just works as expected, and sometimes it gives me the aforementioned empty response.

**Comment by zefer** [comment]
Hi @aedryan. The team are looking into it. In the meantime, please can you drop us an email at support@airbrake.io with the ID or API_KEY of the project in question? Thanks.

**Comment by vmihailenco** [comment]
Hi @aedryan ,

Could you please send the request you are trying to send us to vlad@airbrake.io? I've checked our logs and can't find anything suspicious there.

**Comment by vmihailenco** [comment]
We've made few changes that may help, but it is hard to tell since there is no reliable way to reproduce this. @aedryan thanks for help
