### ISSUE TITLE
how to distinguish onerror wrapper VS manual notify ?

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake-js#587]
I've got a Vue app where I've integrated airbrake-js

From time to time, there are some errors with no backtrace or that are originating from user's browser extensions. 
I'd like to filter those, I think they all come from the `window.onerror` wrapper but before turning the wrapper off, I'd like to be sure.

Is there a way to know if an error comes from the onerror wrapper or from other manual notify ?

I guess I could add something in the vue plugin

**Comment by vmihailenco** [comment]
Errors that are reported from `onerror` handler have `context.windowError == true`. There is also a notifier options called `ignoreWindowError` which just ignores such errors:

```js
let airbrake = new airbrakeJs.Client({
  ignoreWindowError: true,
})
```
