### ISSUE TITLE
@airbrake/node: TypeError: Cannot read property 'Notifier' of undefined

### ISSUE THREAD

**Issue by yoonwaiyan** [airbrake/airbrake-js#590]
Hi, I've installed beta3 version of the node notifier but couldn't make it work for my Node (using Serverless framework). Is there something I'm missing out?

```
  "dependencies": {
    "@airbrake/node": "^1.0.0-beta.3",
  },
```

```javascript
import Airbrake from "@airbrake/node";

// ...

console.log("@airbrake/node", Airbrake); // returns undefined!

// ... 

const airbrake = new Airbrake.Notifier({
//... 
});
```

Btw, how do I use this Notifier without binding the initialization to any call? In Express we can use `app.use()` but in Serverless framework endpoints is this still works?

**Comment by vmihailenco** [comment]
Until now airbrake/node only support cjs build format so you need to use `const Airbrake = require('@airbrake/node');`. I've added support for esm format.

I don't fully understand the part about 'binding the initialization'...
