### ISSUE TITLE
Incomplete Rails example

### ISSUE THREAD

**Issue by teadur** [airbrake/airbrake-js#596]
Currently the  [rails example](https://github.com/airbrake/airbrake-js/blame/master/packages/browser/examples/rails/README.md#L6) includes link to non-existent file as already mentioned in the original pr:
FYI the `dist/client.js` link (https://github.com/airbrake/airbrake-js/blob/master/dist/client.js) returns a 404 in the example.

_Originally posted by @andreierdoss in https://github.com/airbrake/airbrake-js/pull/523#issuecomment-535926285_

For some reason the whole dists folder is removed from the repo, i guess the docu is trying to point to https://github.com/airbrake/airbrake-js/blob/v1.6.8/dist/client.js ?

**Comment by vmihailenco** [comment]
I've fixed the link in https://github.com/airbrake/airbrake-js/tree/master/packages/browser/examples/rails - thanks for the report.
