### ISSUE TITLE
@airbrake/browser airbrake.d.t - TS2304: Cannot find name 'Processor'

### ISSUE THREAD

**Issue by Yaskovich** [airbrake/airbrake-js#600]
Package version: "^1.0.0-beta.7"

Issues in `./node_modules/@airbrake/browser/dist/airbrake.d.ts` file:
`TS2304: Cannot find name 'Processor'`

I see you are already fixed it in https://github.com/airbrake/airbrake-js/commit/9971f640feefcfbe805869ef5a779f2d7412c008

Are there any timelines when it will be released in npm?

**Comment by vmihailenco** [comment]
Done
