### ISSUE TITLE
"export 'default' (imported as 'Airbrake') was not found in '@airbrake/browser'

### ISSUE THREAD

**Issue by HunterMeyer** [airbrake/airbrake-js#601]
**Environment**: Vue
**Version**: @airbrake/browser, 1.0.0

**Description**
Receiving the following warning when running `yarn run serve`

```
warning  in ./src/main.js

"export 'default' (imported as 'Airbrake') was not found in '@airbrake/browser'
```

I have configured airbrake in the main.js file like so:
```js
import Vue from 'vue'
import Airbrake from '@airbrake/browser'

const airbrake = new Airbrake.Notifier({
  projectId: 'HIDDEN',
  projectKey: 'HIDDEN',
  environment: process.env.NODE_ENV,
  keysBlacklist: ['password']
})

Vue.config.errorHandler = function(err, vm, info) {
  airbrake.notify({
    error: err,
    params: { info: info }
  })
}
```

**Comment by vmihailenco** [comment]
Please use `import { Notifier } from '@airbrake/browser'`

**Comment by HunterMeyer** [comment]
@vmihailenco thank you. Please update the documentation so others don't face the same issue I did.

**Comment by HunterMeyer** [comment]
Thenk you for the reply and for updating the documentation, @vmihailenco.
