### ISSUE TITLE
all previous tags was removed

### ISSUE THREAD

**Issue by stolenng** [airbrake/airbrake-js#602]
Could it be that all previous tags was removed ?

**Comment by leungtimothy** [comment]
This is an issue for me as well as bower utilizes git tags to install airbrake-js.

**Comment by stolenng** [comment]
@leungtimothy 
you can use: https://www.npmjs.com/package/bower-npm-resolver ,
and then just `"airbrake-js-client": "npm:@airbrake/browser"`. 
and then load what u need accordingly from there, only change i had to do is `Airbrake.Notifier`

**Comment by leungtimothy** [comment]
@stolenng thanks!

**Comment by kevinmercier** [comment]
> @leungtimothy
> you can use: https://www.npmjs.com/package/bower-npm-resolver ,
> and then just `"airbrake-js-client": "npm:@airbrake/browser"`,
> then load what u need accordingly from there, the only change in JS I had to do is `Airbrake.Notifier`

Does this mean we're forced to use 1.0.0 if our build pipeline was dependent on tags?

**Comment by stolenng** [comment]
They changed the library to  a monorepo with 2 packages for browser and node, you need  to use one of them.

**Comment by vmihailenco** [comment]
>if our build pipeline was dependent on tags

If it depends on git tag you can just replace tag with commit hash. Overall using npm packages is the safest path - all the rest is custom and a bit adventurous.

The only thing that was using git tag was bower but it does not work for long time.
