### ISSUE TITLE
Notifier name change errors when there is no notifier data in the context

### ISSUE THREAD

**Issue by morhekil** [airbrake/airbrake-js#604]
Good day,

we're using `@airbrake/node` package, and we noticed that a move from `1.0.0-beta.7` to `1.0.0` version breaks our notifications with the following error:

```
TypeError: Cannot set property 'name' of undefined
    at nodeFilter (node_modules/@airbrake/node/dist/airbrake.common.js:808:34)
    at Notifier.BaseNotifier.notify (node_modules/@airbrake/node/dist/airbrake.common.js:705:21)
    at Notifier.notify (node_modules/@airbrake/node/dist/airbrake.common.js:1289:40)
```

Looking into the code, the problem seems to coming from the recent commit https://github.com/airbrake/airbrake-js/commit/aa6c14fa65e254d7d512fb553da48dd31a138f10. We raise errors just be calling `notifier.notify("error string")`, and in our case there is no `notifier` object in the notice context - so the name change code errors when trying to change `notifier.name` property.

If I'm reading the code correctly, the notifier data is set [here](https://github.com/airbrake/airbrake-js/blob/aa6c14fa65e254d7d512fb553da48dd31a138f10/packages/browser/src/base_notifier.ts#L115) - only AFTER the filtering is performed, so it seems to make sense that as the point of `filter` calls there isn't any notifier data in the notice yet. Which also suggests that the name change will be overwritten back to `airbrake-js/browser` anyway, even it is successful in the filter.

Is it a problem with our configuration (as in there must always be a notifier in the context, but for some reason it isn't there for us), or should that name change code not make an assumption that the notifier is present?

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/airbrake/airbrake-js/commit/ba833e5019a318c405b396a2e81306ea77597f89
