### ISSUE TITLE
pg instrumentation creates orphaned promise

### ISSUE THREAD

**Issue by adriantrunzo** [airbrake/airbrake-js#607]
The pg instrumentation is creating an orphaned promise that does not have a catch or rejection handler:

https://github.com/airbrake/airbrake-js/blob/8be9acaea4a9e757d0ebab7eb04bdee7317f425d/packages/node/dist/instrumentation/pg.js#L50

If the original SQL query passed to pg.Client.query fails for some reason (eg duplicate key), the promise branch created above will also get rejected. Because the call to `endSpan` is being called within a separate promise, the rejection will show up as unhandled regardless of what error handling we attach to the promise returned by the patched `abQuery`.

I would suggest either adding a `.catch` and leaving the statement as a new promise (preferred):

```
        else if (typeof query.then === 'function') {
            query.then(endSpan).catch(endSpan);
        }
```

Or alternatively, not creating a new promise branch:

```
        else if (typeof query.then === 'function') {
            query = query.then(function(result) {
              endSpan()
              return result
           }).catch(function (e) {
             endSpan()
             throw e
          });
        }
```

You might want more cleanup to happen in the catch. I don't know enough about the `airbrake.scope().routeMetric()` object.

**Comment by vmihailenco** [comment]
Thanks for the detailed explanation - it indeed was needed since I was not aware of such behavior :+1:
