### ISSUE TITLE
Error: Unable to resolve module `async_hooks`

### ISSUE THREAD

**Issue by builtbyproxy** [airbrake/airbrake-js#610]
Hello

I am attempting to run `@airbrake/node` in my react-native project. The versions I am running are: 
- React-Native: 0.61.2
- @airbrake/node: 1.0.2

When I run my mobile app with this install and using the notifier, I get the error:
`Error: Unable to resolve module async_hooks from node_modules/@airbrake/node/dist/airbrake.common.js`

Do I need to install async_hooks? It's not present in any of the package.json files in either browser, node or airbrake-js in general. 

Happy to do a PR if that is the case

Thanks

**Comment by vmihailenco** [comment]
async_hooks is a Node.js core module - it should be available automatically.

Why don't you use @airbrake/browser with React native? I am not familiar with React native so I can miss something obvious...

**Comment by builtbyproxy** [comment]
Ive pivoted from browser because of the error I mentioned here: 
https://github.com/airbrake/airbrake-js/issues/485

Lets continue that conversation here? 

Hey I run this: 

```
const { Notifier } = require('@airbrake/browser');
this.airbrake = new Notifier({
  projectId: '12345',
  projectKey: 'something secret',
  environment: 'production',
});

```

**Comment by vmihailenco** [comment]
>Hey I run this:

It seems to be the right thing to do - are there any issues?

**Comment by builtbyproxy** [comment]
@vmihailenco 
When I run this I now get unexpected errors such as `ReferenceError: window is not defined`

**Comment by builtbyproxy** [comment]
Update, this wasn't anything to do with Airbrake sorry, my jest was running as well and I was getting this error from tests. 

The fix was to add to my jest config in my `package.json`: 
```
"globals": {
    "window": {}
  }
```
