### ISSUE TITLE
Protect against document.location being null

### ISSUE THREAD

**Issue by michowski** [airbrake/airbrake-js#612]
Hi! Our app is using airbrake directly in the NextJs's App's `componentDidCatch` and so it catches 100% of our client-side errors. However, due to our E2E environment (cypress) being unstable, `document.location` may happen to be `null`. I believe it results sporadically in the uncaught `Cannot read property 'pathname' of null` we're experiencing, which I highly suspect is the airbrake function itself! :)

I've noticed in the `node_modules/airbrake-js/dist/client.js` that there isn't any protection against it. Could it be added?

Hopefully it's acceptable that I link the competition to showcase that the issue is real and the solution to it is fairly simple:

https://github.com/getsentry/sentry-javascript/issues/356

**Comment by michowski** [comment]
Hi @vmihailenco, thank you for your quick reaction! May I know how long does it take until it makes it onto an npm release?

**Comment by vmihailenco** [comment]
Just pushed v1.0.4

**Comment by michowski** [comment]
Thank you very much! 🙇
