### ISSUE TITLE
how to use multiple errors in one notice ?

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake-js#630]
Is it possible to `airbrake.notify` with multiple errors at once ?

In my experiences, the stacktrace of errors thrown by ajax libraries do not have anything to do with our code

ex : complete stacktrace of an axios error
```
node_modules/axios/lib/core/createError.js:16:15 in createError
node_modules/axios/lib/core/settle.js:17:12 in settle
node_modules/axios/lib/adapters/http.js:236:11 in IncomingMessage.handleStreamEnd
events.js:203:15 in IncomingMessage.emit
domain.js:448:20 in IncomingMessage.EventEmitter.emit
_stream_readable.js:1145:12 in endReadableNT
internal/process/next_tick.js:63:19 in process._tickCallback
```
nothing from my app

airbrake v3 API can contain multiple errors per notice

It would be nice to be able to either
- create our own new error and `airbrake.notify([myError, axiosError])`
- or create a new custom error `myError` with a `cause` property for example, containing the underlaying `axiosError` (airbrake would check for that `cause` prop and add underlaying error in notice)

myError would have my app backtrace
axiosError still contains the xhr details

It is already used in ruby where exceptions have a [cause](https://ruby-doc.org/core-2.5.0/Exception.html#method-i-cause) method returning the previous error 
and [airbrake-ruby use it to create the notice](https://github.com/airbrake/airbrake-ruby/blob/e2d63a623d7bba7958cb5d9cc1091e0f362f9be9/lib/airbrake-ruby/nested_exception.rb#L32)

**Comment by kyrylo** [comment]
Hi Mathieu!

I think that's a great idea. Can you help me understand how to obtain `cause` from an axios error? I set up a test Angular app and made a request to a non-existent endpoint. It threw a 404, that's expected. However, when I inspect the backtrace, it doesn't belong to my code

<img width="440" alt="1" src="https://user-images.githubusercontent.com/1079123/205096576-ad1834d4-99c0-4ee7-8731-4f5835f54ae3.png">

I can see that the library does support `cause`:
https://github.com/axios/axios/blob/9041c7d272a7d4c3ca416fcb12daf8e94240494d/index.d.ts#L373

We can implement support for [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) in JavaScript, but I would like to have a real-world example that makes use of that property.

**Comment by kyrylo** [comment]
I am happy to look into the `cause` support for airbrake-js but I would like to see any real-world libraries that make use of this property.

If you want to improve axios backtraces, you can use the following plugin: https://github.com/svsool/axios-better-stacktrace

There are some other solutions mentioned in:
* https://github.com/axios/axios/issues/2387
* https://rafaelalmeidatk.com/blog/improving-axios-errors-with-useful-stack-traces
