### ISSUE TITLE
React error boundary errors are not actually sent

### ISSUE THREAD

**Issue by frehner** [airbrake/airbrake-js#631]
Following the docs here https://github.com/airbrake/airbrake-js/tree/master/packages/browser/examples/react

I tried adding params to the notify call but they never showed up in Airbrake. I then discovered that they aren't sent in the network API call either. Further digging revealed the following:

1. `window.onerror` is being called _before_ the React error boundary is being called
2. When the error is caught by the error boundary, it tries to notify again. However, there is a filter built in called `makeDebounceFilter` that prevents the React error boundary error from actually being sent

So, it appears that you either need to turn off `window.onerror` for React apps or find another way to report the errors caught by error boundaries?

**Comment by frehner** [comment]
Turns out that adding `{ignoreWindowError: true}` itself throws an error:

```
opt.instrumentation is undefined
```
on this line https://github.com/airbrake/airbrake-js/blob/master/packages/browser/src/notifier.ts#L50

looks like it supposed to be deprecated

**Comment by frehner** [comment]
ah. it appears that when react is in dev mode, it _throws the error again_ (to go to `window.onerror`) and then catches the new one that it threw. 

In production mode, react doesn't throw again so the boundary should be the only one that reports it. 

[source: react issues](https://github.com/facebook/react/issues/12897#issuecomment-410036991)

**Comment by sgray** [comment]
Hi, @frehner. Were you able to get this issue sorted out? I'm unclear on whether or not there is a problem here.

**Comment by frehner** [comment]
I thought that had solved it, but from what I’ve been seeing it still appears that the window.onerror handler is catching the error most of the time, instead of the error boundary. Which means I’m missing out on the additional information the error boundary adds but the window handler doesn’t

**Comment by sgray** [comment]
>the window.onerror handler is catching the error most of the time, instead of the error boundary

Can you please elaborate on this? I'm confused by the "most of the time" part. Under what circumstances does the error boundary catch the error instead of the `window.onerror` handler?

**Comment by frehner** [comment]
Looking through the airbrake error log for a project, it appears that none of the errors that I looked through were caught by the ErrorBoundary and instead all were caught by the window.onerror listener. 

I'll try clean some stuff up with the ErrorBoundary, and possibly also add a `console.error('in error boundary')` in the render of the ErrorBoundary (which should then be added to the breadcrumbs of the error, right?) to try and debug if the ErrorBoundary is being rendered but not catching it, or if something else is at play here.

**Comment by sgray** [comment]
Sounds good. Yep, your `console.error` should be added to the Breadcrumbs. Let me know how it goes.

**Comment by frehner** [comment]
Things are looking good after cleaning some stuff up. I'll close this for now; thanks for your help.

**Comment by adititipnis** [comment]
@frehner can you elaborate on how did you fix this?

**Comment by r4geee** [comment]
> @frehner can you elaborate on how did you fix this?

```
airbrake = new Notifier({
    environment,
    ignoreWindowError: true,
    instrumentation: {
      fetch: true,
      history: true,
      xhr: true,
    },
    projectId,
    projectKey,
  });
```

I had the same issue and this seems to have fixed it
