### ISSUE TITLE
Bug "can not report routes stats"

### ISSUE THREAD

**Issue by jgelsey** [airbrake/airbrake-js#668]
airbrake.js fails with:
`can not report routes stats Error: json: cannot unmarshal object into Go struct field RouteStatStage.routes.route of type string
    at /home/ubuntu/sharelock/node_modules/@airbrake/browser/dist/http_req/fetch.js:47:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
More complete logs attached here:
[airbrake-error-log.txt](https://github.com/airbrake/airbrake-js/files/4535696/airbrake-error-log.txt)

Details: `Sharelock` is an OSS utility from Auth0 to share secrets - the utility creates a URL from a secret that can only be decoded by someone with credentials specified when the URL is created.  It's quite handy for sending around passwords etc.

_To reproduce:_

A. Create a new AWS free tier Ubuntu micro instance.  Say this has IP address "x.y.z.w".  Open port 3000
B. Create a free throwaway Auth0 account, add x.y.z.w:3000/callback to the list of allowed callback URLs for "Default App".  You'll need the AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET from the settings of "Default App".
C. Create a free throwaway Airbrake account.  You'll need an AIRBRAKE_PROJECT_ID and the 
AIRBRAKE_PROJECT_KEY.
D. In the AWS shell:

`      1  git clone https://github.com/jgelsey/sharelock`
`    2  cd sharelock/`
`    3. cp .env.sample .env`
`    4  vi .env`
`   5 sudo apt update`
`   6  sudo apt full-upgrade`
`   7  sudo apt install nodejs`
`   8  sudo apt install npm`
`   9  npm install dotenv`
`   10  npm start | ./node_modules/.bin/bunyan `

The .env file requires the AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET, AIRBRAKE_PROJECT_ID, AIRBRAKE_PROJECT_KEY.  In `.env`, the COOKIE_SECRET, ENCRYPTION_KEY_1 and SIGNATURE_KEY_1 can be any arbitrary 32 char hex strings generated on the CLI with `openssl rand -hex 32`, and AUTH0_CALLBACK is `http://x.y.z.w:3000/callback`.

**Comment by sgray** [comment]
Thanks for the detailed report. I've identified the problem and will work on getting a fix released as soon as possible.

**Comment by jgelsey** [comment]
Thanks for the quick response, Steve!

**Comment by sgray** [comment]
👍 No problem. Just released v1.1.1. Please give it a try and let us know if you run into any other issues.

**Comment by jgelsey** [comment]
BTW your fix works great, thanks again for the quick resolution.
