### ISSUE TITLE
Extract core functionality into a new package

### ISSUE THREAD

**Issue by sgray** [airbrake/airbrake-js#702]
Currently, `@airbrake/node` relies on `@airbrake/browser`, which isn't ideal. An `@airbrake/core` package should be extracted so any shared functionality can reside there and the `browser` and `node` packages can have better separation.

**Comment by scottsbaldwin** [comment]
@sgray, can you please add an estimate label to this issue?

**Comment by akauppi** [comment]
This looks like work-as-usual to me, however is undone 4 months later.

Does this show general disregard on the JavaScript client, by Airbrake? If so, I better look for alternatives that are well maintained.

**Comment by scottsbaldwin** [comment]
Hi @akauppi, we had to prioritize some other work above this issue. That other work is finishing up soon though and then we can pick this up.
