### ISSUE TITLE
README documentation errors

### ISSUE THREAD

**Issue by GimpMaster** [airbrake/airbrake-js#731]
I noticed in the README a couple issues.

The first one is in the first paragraph where it says if you are looking for the node-js version click here. However this README IS for the node-js version. I'm guess you meant to say if you are looking for the browser version click here.

Also another issue is with the example of try/catch code example as seen below

```
try {
  new Error('Hello from Airbrake!');
} catch(err) {
  airbrake.notify(err);
  throw err;
}
```

I believe it should look like this.

```
try {
  throw new Error('Hello from Airbrake!');

} catch(err) {
  airbrake.notify(err);
}
```

**Comment by sgray** [comment]
Thanks, @GimpMaster. I'll get those cleaned up.
