### ISSUE TITLE
Rename keysBlacklist

### ISSUE THREAD

**Issue by sgray** [airbrake/airbrake-js#749]
The technology industry has began moving away from terms such as master/slave and whitelist/blacklist.

- https://github.com/rails/rails/issues/33677
- https://github.com/airbrake/airbrake-ruby/pull/580
- https://twitter.com/leahculver/status/1269109776983547904

**Comment by froozeapp** [comment]
What's the problem with the terminology? It basicallly describes the functions. What if someone has a "Masters Degree" is that bad?
