### ISSUE TITLE
Cannot read property '_ignoreNextWindowError' of undefined

### ISSUE THREAD

**Issue by ryan2johnson9** [airbrake/airbrake-js#790]
```
  function causeError(){
    throw new Error('Hello from Airbrake!');
  }
  causeError = airbrake.wrap(causeError);
  causeError();
```
Successfuly reports my error but also reports an error from within the airbrake.js code:

`TypeError:  Cannot read property '_ignoreNextWindowError' of undefined`

which is from this part of the Airbrake code:

```
      var airbrakeWrapper = function () {
        var fnArgs = Array.prototype.slice.call(arguments);
        var wrappedArgs = client._wrapArguments(fnArgs);
        try {
          return fn.apply(this, wrappedArgs);
        }
        catch (err) {
          client.notify({ error: err, params: { arguments: fnArgs } });
          this._ignoreNextWindowError();
          throw err;
        }
      };
```

I downloaded that from https://unpkg.com/@airbrake/browser@1.4.0/umd/airbrake.js
as suggested in this help page:
https://airbrake.io/docs/installing-airbrake/installing-airbrake-js-in-a-rails-app/

however standard notfying works fine with

```

try {
  throw new Error('Hello from Airbrake! JS error should have development env');
} catch (err) {
  airbrake.notify(err).then(function(notice) {
    if (notice.id) {
      console.log('notice id:', notice.id);
    } else {
      console.log('notify failed:', notice.error);
    }
  });
}
```

**Comment by Thunberg087** [comment]
I opened a Pull Request related to this issue. Needs testing. https://github.com/airbrake/airbrake-js/pull/944

**Comment by kyrylo** [comment]
Nice one, I confirmed that #944 fixed the issue 👍
