### ISSUE TITLE
Integration with next.js gives Module not found: Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by AbdallahBedir** [airbrake/airbrake-js#814]
# 🐞 bug report

### Affected Package

The issue is caused by package @airbrake/node

### Is this a regression?

No

### Description
When I use @airbrake/node with next.js, I always got
`error - ./node_modules/@airbrake/node/esm/scope.js:2:0
Module not found: Can't resolve 'async_hooks'`
I hope you create an example of integration with next.js

## 🔥 Exception or Error
<pre>error - ./node_modules/@airbrake/node/esm/scope.js:2:0
Module not found: Can't resolve 'async_hooks'<code>

## 🌍  Your Environment

**@airbrake/\* version:**
<pre><code>

@airbrake/node v1.4.1

**Comment by mirzapourh** [comment]
Any ideas when this will be resolved?

**Comment by AbdallahBedir** [comment]
@mirzapourh  If you work with next.js, check this example with sentry https://github.com/vercel/next.js/tree/canary/examples/with-sentry

**Comment by thompiler** [comment]
Hi @AbdallahBedir,

Would it be possible for you to import the `@airbrake/node` package on the `_error.js` page only when running on the server? Here's an example of what worked in my own testing:

## Example of `pages/_error.js` 

```js
Error.getInitialProps = ({ req, res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404

  if (!process.browser) {
    const Airbrake = require('@airbrake/node')

    const airbrake = new Airbrake.Notifier({
      projectId: 123,
      projectKey: 'asdf123',
    })


    if (err) {
      airbrake.notify(err)
    }
  }
  return { statusCode }
}
export default Error
```

## Example of `pages/_error.js` that has the reported issue

```js
// This general import replicated the issue for me
import { Airbrake } from '@airbrake/node'

Error.getInitialProps = ({ req, res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404

  if (!process.browser) {
    const airbrake = new Airbrake.Notifier({
      projectId: 123,
      projectKey: 'asdf1234',
    })


    if (err) {
      airbrake.notify(err)
    }
  }
  return { statusCode }
}
export default Error
```

**Comment by thompiler** [comment]
Hi @AbdallahBedir, I believe we've addressed your question but please feel free to reopen this issue if you have any pending questions or problems.

We'll work on adding a Next.js example to list too. 👍

**Comment by AbdallahBedir** [comment]
Hello @thompiler 
Thanks but how can I upload the source maps to have meaningful errors in production?

**Comment by thompiler** [comment]
Hi @AbdallahBedir! Here's our doc on uploading source maps to Airbrake: https://airbrake.io/docs/features/private-sourcemaps/
