### ISSUE TITLE
Use zone.js to instrument browser interaction points

### ISSUE THREAD

**Issue by duncanbeevers** [airbrake/airbrake-js#82]
@vmihailenco @dvdplm @benarent 
I suggest we look into using [zone.js](https://github.com/btford/zone.js/) to hook into all the browser points from whence code could be executed, automatically generating `Airbrake.wrap` closures around them.

**Comment by dandv** [comment]
That would be awesome for a "set it and forget it" setup. Now I have to add try/catch blocks everywhere.

**Comment by dandv** [comment]
That would be awesome for a "set it and forget it" setup. Now I have to add try/catch blocks everywhere.

Loggly has that feature: https://www.loggly.com/docs/javascript/

**Comment by vmihailenco** [comment]
I still don't understand what should be done here. Looking at https://github.com/btford/zone.js/ integration is as simple as adding `onError` hook, but probably I miss something.

>Loggly has that feature: https://www.loggly.com/docs/javascript/

I can't find anything about zone.js on that page. Can you please be more specific?

**Comment by dandv** [comment]
As far as I'm concerned, it looks like just adding an `onerror` handler, similar to the [catchall parameter for LogEntries](https://github.com/logentries/le_js/wiki/API), will do the trick.

Maybe @duncanbeevers can comment on the zone.js idea?

**Comment by szepeviktor** [comment]
I think this is the minimalist implementation:
```js
window.onerror = function(msg, url, line, col, error) {
   // Note that col & error are new to the HTML 5 spec and may not be 
   // supported in every browser.  It worked for me in Chrome.
   var extra = !col ? '' : '\ncolumn: ' + col;
   extra += !error ? '' : '\nerror: ' + error;

   // You can view the information in an alert to see things working like this:
   alert("Error: " + msg + "\nurl: " + url + "\nline: " + line + extra);

   // TODO: Report this error via ajax so you can keep track
   //       of what pages have JS issues

   var suppressErrorAlert = true;
   // If you return true, then error alerts (like in older versions of 
   // Internet Explorer) will be suppressed.
   return suppressErrorAlert;
};
```

**Comment by vmihailenco** [comment]
Closing since there is no understanding what should be done.
