### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by benjclark** [airbrake/airbrake-js#832]
# 🐞 bug report

### Affected Package
The issue is caused by package @airbrake/browser

### Is this a regression?
No

### Description
If I `import { Notifier } from @airbrake/browser` and bundle using Rollup and the Rollup plugins needed to process your package code then I see `Uncaught ReferenceError: global is not defined` in the browser when the bundle is executed.

## 🔬 Minimal Reproduction
I have created a demo repo for you: https://github.com/benjclark/rollup-commonjs-airbrake

Steps:
1. npm install
2. run `node ./node_modules/gulp/bin/gulp.js bundle`
3. take the contents of output/dist.js and copy and paste in to a `<script>` on a local page you have running and reload

You will see the error `Uncaught ReferenceError: global is not defined`.

## 🔥 Exception or Error
`Uncaught ReferenceError: global is not defined`

## 🌍  Your Environment
 ``` 
"dependencies": {
    "@airbrake/browser": "^1.4.1"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^15.0.0",
    "@rollup/plugin-node-resolve": "^9.0.0",
    "gulp": "^4.0.2",
    "rollup": "^2.26.11",
    "rollup-plugin-node-builtins": "^2.1.2"
  }
```

**Anything else relevant?**
I have also tried babelifying your code during the bundling but it did not solve the issue.

I have also tried the Rollup plugin https://github.com/leebyron/rollup-plugin-async but it did not fix the issue either.

**Comment by mercmobily** [comment]
I am having the same problem, and this is a _huge_ showstopper... any news on this one?

**Comment by mercmobily** [comment]
Sorry, I meant to write this comment on a VERY similar issue on RollUp...

**Comment by kyrylo** [comment]
Hello! 

Sorry for the late reply. Thank you for the example repository. It was really helpful. I was able to reproduce the issue.
It doesn't look like a problem with `@airbrake/browser`. I tried to change certain variables but it didn't fix anything. It must be an issue with a transient dependency.

@mercmobily could you link to the issue?

I am afraid, I cannot help here because it seems to be a Rollup issue.
