### ISSUE TITLE
@airbrake/node - enable async_hooks by default

### ISSUE THREAD

**Issue by yosiat** [airbrake/airbrake-js#892]
Hi,

I upgraded from airbrake-js to `@airbrake/node`,  in high traffic service we saw a huge performance degradation which seems to happen by enabling async_hooks by default.

Important to mention - that in the past, for the exact service we enabled async_hooks and saw a performance degradation.

Is it possible to use `@airbrake/node` with async_hooks disabled (and without the overhead of the performance instrumentation) ?

I can submit a PR if the idea makes sense to you.

**Comment by scottsbaldwin** [comment]
@yosiat, we'll take a deeper look and investigate. Thanks for letting us know.

**Comment by yosiat** [comment]
quick update: we did the redeploy of the changes we did yesterday, but with airbrake-js and not airbrake/node and we had no performance regression.

@scottsbaldwin if you want, I can try and make a PR that will initialise the scope manager only if performance stats is enabled.

**Comment by scottsbaldwin** [comment]
@yosiat that would be great to see your PR!

**Comment by yosiat** [comment]
@scottsbaldwin created a PR here - https://github.com/airbrake/airbrake-js/pull/894

let me know what you think about it!
