### ISSUE TITLE
Provide a Bower component

### ISSUE THREAD

**Issue by jhabdas** [airbrake/airbrake-js#95]
Other error reporting tools such as Honeybadger provide [a bower component](/github.com/honeybadger-io/honeybadger-js) enabling developers to pull in code as a versioned component, e.g. `bower install --save honeybadger.js` and you're done.

But running `bower search airbrake` turns up `nil`. The current drop-in SCRIPT tag technique is bad because it advocates use of blocking scripts which lead to front-end SPOF. As a result, I'm open this issue so that a bower module is created for easier (and better) client-side consumption in JS apps (i.e. single-page apps.

**Comment by aguynamedben** [comment]
+1

**Comment by eddywashere** [comment]
If anyone is interested in what this might look like, I put together a gist of what a 3rd party async loader would look like, based on google analytics example. 

https://gist.github.com/eddywashere/dc5627693cf9ff4355e0

**Comment by aguynamedben** [comment]
Actually I was able to get airbrake-js installed on bower... it's not listed on the official bower site, but you can do

```bower search airbrake-js```

and add this to your bower.json...

```
{
  "name": "network",
  "dependencies": {
    "airbrake-js": "1.4.1"
  }
}
```

This is probably just downloading the dist folder for usage. I'm far from an expert on JS async loading.

**Comment by aguynamedben** [comment]
Actually, yeah I thought I could get this working because you can install airbrake-js via bower, but there is no dist/ folder that lets you access a compile version of the client. It's amazing that it's not easy to get Airbrake JS reporting working on a simple Rails app...

**Comment by aguynamedben** [comment]
Are there any simple docs on how to get this working on a Rails app? I have never used RequireJS, I use Bower to install front-end components (or Rails gems if I really have to). There is no dist/ folder provided with compiled code, no working bower component, and no Rails gem. I don't understand how I'm supposed to get this working on a simple Rails app. Isn't that the most common use case?

**Comment by vmihailenco** [comment]
We use `npm install airbrake-js`. I am checking how hard it will be to make notifier available using Bower.

**Comment by vmihailenco** [comment]
Also

```
bower install airbrake-js-client
```

should work too.

**Comment by aguynamedben** [comment]
Ah yeah it's there now, woot https://github.com/airbrake/airbrake-js/blob/master/bower.json @vmihailenco :+1:

**Comment by jhabdas** [comment]
Closing. Reopen if needed.

**Comment by HadrienPierart** [comment]
Hi guys,
Great product. I just tried adding it through bower and it doesnt seem to work. 
When building with grunt and injecting bower scripts, the path is broken and I cant figure why the path is wrong...
Any idea why this is ?

I did a simple :
`bower install airbrake-js-client --save`

And then, the injected script was :
`bower_components/airbrake-js-dist/client.js`

which obvisouly doesnt work, as the path is : `bower_components/airbrake-js-client/dist/client.js`

**Comment by vmihailenco** [comment]
Hi,

How do you compile your app? Which lib is responsible for injecting `bower_components/airbrake-js-dist/client.js`?

**Comment by MagicIndustries** [comment]
I'm having the same problem as @HadrienPierart 

I use grunt to compile the app, with wiredep doing the injection.

**Comment by vmihailenco** [comment]
@MagicIndustries I've added gulp+bower+wiredep example and it seems to work https://github.com/airbrake/airbrake-js/pull/173. So I need more details to fix this issue...

**Comment by shime** [comment]
Closing this one since it should be fixed. Reopen if this is still an issue.

**Comment by jhabdas** [comment]
I urge watchers of this thread to please stop using Bower if you can in favor of NPM. Those looking to add analytics and error monitoring to their apps may want to look at look at segment.com and their hundreds of integrations. Alternatively, Browserify supports a SaaS to convert NPM modules for use in the browser.
